// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'editing_api.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `close`, `core_selection`, `disclosure_digest`, `ensure_open`, `event_kind_name`, `handle`, `join_worker`, `native_event`, `native_run`, `native_selection_context`, `new`, `parse_run_id`, `status_name`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NativeAgentRuntime`, `NativeRunHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class NativeAgentAudit {
  final int schemaVersion;
  final String runId;
  final String status;
  final List<NativeAgentEvent> events;

  const NativeAgentAudit({
    required this.schemaVersion,
    required this.runId,
    required this.status,
    required this.events,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      runId.hashCode ^
      status.hashCode ^
      events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeAgentAudit &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          runId == other.runId &&
          status == other.status &&
          events == other.events;
}

class NativeAgentEvent {
  final int schemaVersion;
  final String sessionId;
  final String runId;
  final BigInt sequence;
  final BigInt documentRevision;
  final String kind;
  final String payloadJson;

  const NativeAgentEvent({
    required this.schemaVersion,
    required this.sessionId,
    required this.runId,
    required this.sequence,
    required this.documentRevision,
    required this.kind,
    required this.payloadJson,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      sessionId.hashCode ^
      runId.hashCode ^
      sequence.hashCode ^
      documentRevision.hashCode ^
      kind.hashCode ^
      payloadJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeAgentEvent &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          sessionId == other.sessionId &&
          runId == other.runId &&
          sequence == other.sequence &&
          documentRevision == other.documentRevision &&
          kind == other.kind &&
          payloadJson == other.payloadJson;
}

class NativeAgentRun {
  final int schemaVersion;
  final String runId;
  final String status;

  const NativeAgentRun({
    required this.schemaVersion,
    required this.runId,
    required this.status,
  });

  @override
  int get hashCode => schemaVersion.hashCode ^ runId.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeAgentRun &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          runId == other.runId &&
          status == other.status;
}

class NativeSelectionContext {
  final int schemaVersion;
  final String documentId;
  final BigInt revision;
  final NativeSelectionKind kind;
  final List<NativeSelectionRange> ranges;
  final Uint32List pageNumbers;
  final String nearbyTextBefore;
  final String nearbyTextAfter;
  final String disclosureSha256;

  const NativeSelectionContext({
    required this.schemaVersion,
    required this.documentId,
    required this.revision,
    required this.kind,
    required this.ranges,
    required this.pageNumbers,
    required this.nearbyTextBefore,
    required this.nearbyTextAfter,
    required this.disclosureSha256,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      documentId.hashCode ^
      revision.hashCode ^
      kind.hashCode ^
      ranges.hashCode ^
      pageNumbers.hashCode ^
      nearbyTextBefore.hashCode ^
      nearbyTextAfter.hashCode ^
      disclosureSha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSelectionContext &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          documentId == other.documentId &&
          revision == other.revision &&
          kind == other.kind &&
          ranges == other.ranges &&
          pageNumbers == other.pageNumbers &&
          nearbyTextBefore == other.nearbyTextBefore &&
          nearbyTextAfter == other.nearbyTextAfter &&
          disclosureSha256 == other.disclosureSha256;
}

class NativeStartAgentRunRequest {
  final int schemaVersion;
  final String providerEndpoint;
  final String modelId;
  final Map<String, String> headers;
  final String apiKey;
  final String? conversationId;
  final String userPrompt;
  final NativeSelectionSet selection;
  final String disclosureSha256;
  final int maxToolCalls;
  final int maxProviderRounds;
  final BigInt maxElapsedMs;
  final int maxOutputTokens;

  const NativeStartAgentRunRequest({
    required this.schemaVersion,
    required this.providerEndpoint,
    required this.modelId,
    required this.headers,
    required this.apiKey,
    this.conversationId,
    required this.userPrompt,
    required this.selection,
    required this.disclosureSha256,
    required this.maxToolCalls,
    required this.maxProviderRounds,
    required this.maxElapsedMs,
    required this.maxOutputTokens,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      providerEndpoint.hashCode ^
      modelId.hashCode ^
      headers.hashCode ^
      apiKey.hashCode ^
      conversationId.hashCode ^
      userPrompt.hashCode ^
      selection.hashCode ^
      disclosureSha256.hashCode ^
      maxToolCalls.hashCode ^
      maxProviderRounds.hashCode ^
      maxElapsedMs.hashCode ^
      maxOutputTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeStartAgentRunRequest &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          providerEndpoint == other.providerEndpoint &&
          modelId == other.modelId &&
          headers == other.headers &&
          apiKey == other.apiKey &&
          conversationId == other.conversationId &&
          userPrompt == other.userPrompt &&
          selection == other.selection &&
          disclosureSha256 == other.disclosureSha256 &&
          maxToolCalls == other.maxToolCalls &&
          maxProviderRounds == other.maxProviderRounds &&
          maxElapsedMs == other.maxElapsedMs &&
          maxOutputTokens == other.maxOutputTokens;
}
