// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'chat_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `chat_endpoint`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

Stream<NativeChatEvent> streamChat({required NativeChatRequest request}) =>
    RustLib.instance.api.crateChatApiStreamChat(request: request);

Future<NativeChatEvent?> parseChatSseData({required String data}) =>
    RustLib.instance.api.crateChatApiParseChatSseData(data: data);

@freezed
sealed class NativeChatEvent with _$NativeChatEvent {
  const NativeChatEvent._();

  const factory NativeChatEvent.textDelta({required String text}) =
      NativeChatEvent_TextDelta;
  const factory NativeChatEvent.error({required String message}) =
      NativeChatEvent_Error;
  const factory NativeChatEvent.done() = NativeChatEvent_Done;
}

class NativeChatMessage {
  final String role;
  final String content;

  const NativeChatMessage({required this.role, required this.content});

  @override
  int get hashCode => role.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeChatMessage &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content;
}

class NativeChatRequest {
  final String providerEndpoint;
  final String modelId;
  final Map<String, String> headers;
  final String apiKey;
  final List<NativeChatMessage> messages;

  const NativeChatRequest({
    required this.providerEndpoint,
    required this.modelId,
    required this.headers,
    required this.apiKey,
    required this.messages,
  });

  @override
  int get hashCode =>
      providerEndpoint.hashCode ^
      modelId.hashCode ^
      headers.hashCode ^
      apiKey.hashCode ^
      messages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeChatRequest &&
          runtimeType == other.runtimeType &&
          providerEndpoint == other.providerEndpoint &&
          modelId == other.modelId &&
          headers == other.headers &&
          apiKey == other.apiKey &&
          messages == other.messages;
}
