// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'agent_api.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `adapter_error`, `affine_transform`, `editing_error`, `editor_command`, `native_annotation_from_core`, `native_annotation_request`, `native_annotation`, `native_box`, `native_command_result`, `native_event`, `native_object_patch`, `native_scene_object`, `native_search_mode`, `native_selection_kind_to_native`, `native_selection_kind`, `native_selection_range_from_core`, `native_selection_range`, `native_text_run`, `native_transform`, `parse_object_id`, `pdf_box`, `persist_fallback_asset`, `replace_utf16`, `required`, `submit_annotation_command`, `text_style`, `viewport_priority`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NativeDirtyTile`, `NativeTileInvalidation`, `PendingFontFallback`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativeEditorSession>>
abstract class NativeEditorSession implements RustOpaqueInterface {
  Stream<NativeAgentEvent> agentEvents({required String runId});

  Future<NativeAnnotation> annotationDetails({required String objectId});

  Future<NativeAgentRun> approveAgentProposal({
    required String runId,
    required String approvalId,
  });

  Future<NativeCommandResult> approveFontFallback({
    required NativeApproveFontFallbackRequest request,
  });

  Future<void> cancelAgentRun({required String runId});

  Future<NativeCommandResult> checkpoint({
    required NativeCheckpointRequest request,
  });

  Future<NativeCleanPatchAsset> cleanPatch({
    required NativeCleanPatchRequest request,
  });

  Future<void> close();

  Future<NativeCompatibilityReport> compatibilityReport({
    required BigInt expectedRevision,
  });

  Future<NativeCommandResult> createAnnotation({
    required NativeAnnotationCommandRequest request,
  });

  Future<NativeCommandResult> deleteAnnotation({
    required NativeDeleteAnnotationRequest request,
  });

  Stream<NativeEditorEvent> events();

  Future<NativeConversationImportReceipt> importAgentConversation({
    required NativeConversationImport value,
  });

  Future<NativeEditorMetadata> metadata();

  Future<NativeSceneObject> objectDetails({
    required NativeObjectDetailsRequest request,
  });

  static Future<NativeEditorSession> open({
    required NativeOpenEditorRequest request,
  }) => RustLib.instance.api.crateEditingApiNativeEditorSessionOpen(
    request: request,
  );

  Future<NativePageScene> pageScene({required NativePageSceneRequest request});

  Future<NativeFontFallbackProposal> proposeFontFallback({
    required NativeFontFallbackProposalRequest request,
  });

  Future<NativeAgentAudit> readAgentAudit({required String runId});

  Future<NativeAgentRun> rebaseAgentProposal({
    required String runId,
    required String approvalId,
    required BigInt currentRevision,
  });

  Future<NativeAgentRun> rejectAgentProposal({
    required String runId,
    required String approvalId,
  });

  Future<void> releaseCleanPatchMemory();

  Future<void> reportMemoryPressure({required NativeMemoryPressureLevel level});

  Future<NativeEditorSaveResult> save({
    required NativeEditorSaveRequest request,
  });

  Future<NativeSearchResult> search({required NativeSearchRequest request});

  Future<NativeSelectionContext> selectionContext({
    required NativeSelectionSet selection,
    required int beforeUtf16,
    required int afterUtf16,
    required int maxRanges,
  });

  Future<NativeAgentRun> startAgentRun({
    required NativeStartAgentRunRequest request,
  });

  Future<NativeCommandResult> submit({
    required NativeSubmitCommandRequest request,
  });

  Future<NativeCommandResult> updateAnnotation({
    required NativeAnnotationCommandRequest request,
  });

  Future<NativeValidatedSelection> validateSelection({
    required NativeSelectionSet selection,
  });
}

class NativeAffineTransform {
  final double a;
  final double b;
  final double c;
  final double d;
  final double e;
  final double f;

  const NativeAffineTransform({
    required this.a,
    required this.b,
    required this.c,
    required this.d,
    required this.e,
    required this.f,
  });

  @override
  int get hashCode =>
      a.hashCode ^
      b.hashCode ^
      c.hashCode ^
      d.hashCode ^
      e.hashCode ^
      f.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeAffineTransform &&
          runtimeType == other.runtimeType &&
          a == other.a &&
          b == other.b &&
          c == other.c &&
          d == other.d &&
          e == other.e &&
          f == other.f;
}

class NativeAnnotation {
  final String objectId;
  final String pageId;
  final NativePdfBox bounds;
  final NativeAnnotationKind kind;
  final NativeAnnotationAnchorKind anchorKind;
  final double? anchorX;
  final double? anchorY;
  final List<NativeAnnotationRange> ranges;
  final String title;
  final String body;
  final Uint8List colorRgba;
  final double opacity;
  final bool resolved;

  const NativeAnnotation({
    required this.objectId,
    required this.pageId,
    required this.bounds,
    required this.kind,
    required this.anchorKind,
    this.anchorX,
    this.anchorY,
    required this.ranges,
    required this.title,
    required this.body,
    required this.colorRgba,
    required this.opacity,
    required this.resolved,
  });

  @override
  int get hashCode =>
      objectId.hashCode ^
      pageId.hashCode ^
      bounds.hashCode ^
      kind.hashCode ^
      anchorKind.hashCode ^
      anchorX.hashCode ^
      anchorY.hashCode ^
      ranges.hashCode ^
      title.hashCode ^
      body.hashCode ^
      colorRgba.hashCode ^
      opacity.hashCode ^
      resolved.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeAnnotation &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          pageId == other.pageId &&
          bounds == other.bounds &&
          kind == other.kind &&
          anchorKind == other.anchorKind &&
          anchorX == other.anchorX &&
          anchorY == other.anchorY &&
          ranges == other.ranges &&
          title == other.title &&
          body == other.body &&
          colorRgba == other.colorRgba &&
          opacity == other.opacity &&
          resolved == other.resolved;
}

enum NativeAnnotationAnchorKind { pagePoint, textRanges }

class NativeAnnotationCommandRequest {
  final int schemaVersion;
  final String commandId;
  final BigInt baseRevision;
  final NativeAnnotation annotation;

  const NativeAnnotationCommandRequest({
    required this.schemaVersion,
    required this.commandId,
    required this.baseRevision,
    required this.annotation,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      commandId.hashCode ^
      baseRevision.hashCode ^
      annotation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeAnnotationCommandRequest &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          commandId == other.commandId &&
          baseRevision == other.baseRevision &&
          annotation == other.annotation;
}

enum NativeAnnotationKind { bookmark, highlight, comment }

class NativeAnnotationRange {
  final String rangeId;
  final String objectId;
  final int startUtf16;
  final int endUtf16;
  final String quotedText;

  const NativeAnnotationRange({
    required this.rangeId,
    required this.objectId,
    required this.startUtf16,
    required this.endUtf16,
    required this.quotedText,
  });

  @override
  int get hashCode =>
      rangeId.hashCode ^
      objectId.hashCode ^
      startUtf16.hashCode ^
      endUtf16.hashCode ^
      quotedText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeAnnotationRange &&
          runtimeType == other.runtimeType &&
          rangeId == other.rangeId &&
          objectId == other.objectId &&
          startUtf16 == other.startUtf16 &&
          endUtf16 == other.endUtf16 &&
          quotedText == other.quotedText;
}

class NativeApproveFontFallbackRequest {
  final int schemaVersion;
  final String commandId;
  final BigInt baseRevision;
  final String proposalToken;

  const NativeApproveFontFallbackRequest({
    required this.schemaVersion,
    required this.commandId,
    required this.baseRevision,
    required this.proposalToken,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      commandId.hashCode ^
      baseRevision.hashCode ^
      proposalToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeApproveFontFallbackRequest &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          commandId == other.commandId &&
          baseRevision == other.baseRevision &&
          proposalToken == other.proposalToken;
}

class NativeCheckpointRequest {
  final BigInt baseRevision;
  final String label;

  const NativeCheckpointRequest({
    required this.baseRevision,
    required this.label,
  });

  @override
  int get hashCode => baseRevision.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeCheckpointRequest &&
          runtimeType == other.runtimeType &&
          baseRevision == other.baseRevision &&
          label == other.label;
}

class NativeCleanPatchAsset {
  final String handle;
  final String objectId;
  final NativePdfBox bounds;
  final int dpi;
  final int width;
  final int height;
  final Uint8List rgbaBytes;
  final double bleedPoints;

  const NativeCleanPatchAsset({
    required this.handle,
    required this.objectId,
    required this.bounds,
    required this.dpi,
    required this.width,
    required this.height,
    required this.rgbaBytes,
    required this.bleedPoints,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      objectId.hashCode ^
      bounds.hashCode ^
      dpi.hashCode ^
      width.hashCode ^
      height.hashCode ^
      rgbaBytes.hashCode ^
      bleedPoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeCleanPatchAsset &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          objectId == other.objectId &&
          bounds == other.bounds &&
          dpi == other.dpi &&
          width == other.width &&
          height == other.height &&
          rgbaBytes == other.rgbaBytes &&
          bleedPoints == other.bleedPoints;
}

class NativeCleanPatchRequest {
  final String objectId;
  final int dpi;

  const NativeCleanPatchRequest({required this.objectId, required this.dpi});

  @override
  int get hashCode => objectId.hashCode ^ dpi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeCleanPatchRequest &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          dpi == other.dpi;
}

class NativeCommandResult {
  final String commandId;
  final BigInt previousRevision;
  final BigInt committedRevision;
  final bool durable;
  final List<String> warnings;
  final List<String> removedObjectIds;
  final NativeSelectionRebase? selectionRebase;
  final List<NativeObjectPatch> objectPatches;

  const NativeCommandResult({
    required this.commandId,
    required this.previousRevision,
    required this.committedRevision,
    required this.durable,
    required this.warnings,
    required this.removedObjectIds,
    this.selectionRebase,
    required this.objectPatches,
  });

  @override
  int get hashCode =>
      commandId.hashCode ^
      previousRevision.hashCode ^
      committedRevision.hashCode ^
      durable.hashCode ^
      warnings.hashCode ^
      removedObjectIds.hashCode ^
      selectionRebase.hashCode ^
      objectPatches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeCommandResult &&
          runtimeType == other.runtimeType &&
          commandId == other.commandId &&
          previousRevision == other.previousRevision &&
          committedRevision == other.committedRevision &&
          durable == other.durable &&
          warnings == other.warnings &&
          removedObjectIds == other.removedObjectIds &&
          selectionRebase == other.selectionRebase &&
          objectPatches == other.objectPatches;
}

class NativeCompatibilityIssue {
  final String objectId;
  final String pageId;
  final String kind;
  final String capability;
  final String code;
  final String message;
  final List<String> supportedOperations;

  const NativeCompatibilityIssue({
    required this.objectId,
    required this.pageId,
    required this.kind,
    required this.capability,
    required this.code,
    required this.message,
    required this.supportedOperations,
  });

  @override
  int get hashCode =>
      objectId.hashCode ^
      pageId.hashCode ^
      kind.hashCode ^
      capability.hashCode ^
      code.hashCode ^
      message.hashCode ^
      supportedOperations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeCompatibilityIssue &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          pageId == other.pageId &&
          kind == other.kind &&
          capability == other.capability &&
          code == other.code &&
          message == other.message &&
          supportedOperations == other.supportedOperations;
}

class NativeCompatibilityReport {
  final int schemaVersion;
  final BigInt revision;
  final int editableCount;
  final int overlayOnlyCount;
  final int readOnlyCount;
  final List<NativeCompatibilityIssue> issues;

  const NativeCompatibilityReport({
    required this.schemaVersion,
    required this.revision,
    required this.editableCount,
    required this.overlayOnlyCount,
    required this.readOnlyCount,
    required this.issues,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      revision.hashCode ^
      editableCount.hashCode ^
      overlayOnlyCount.hashCode ^
      readOnlyCount.hashCode ^
      issues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeCompatibilityReport &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          revision == other.revision &&
          editableCount == other.editableCount &&
          overlayOnlyCount == other.overlayOnlyCount &&
          readOnlyCount == other.readOnlyCount &&
          issues == other.issues;
}

class NativeDeleteAnnotationRequest {
  final int schemaVersion;
  final String commandId;
  final BigInt baseRevision;
  final String objectId;

  const NativeDeleteAnnotationRequest({
    required this.schemaVersion,
    required this.commandId,
    required this.baseRevision,
    required this.objectId,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      commandId.hashCode ^
      baseRevision.hashCode ^
      objectId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeDeleteAnnotationRequest &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          commandId == other.commandId &&
          baseRevision == other.baseRevision &&
          objectId == other.objectId;
}

class NativeEditorCommand {
  final NativeEditorCommandKind kind;
  final String? objectId;
  final int? start;
  final int? end;
  final String? replacement;
  final NativeTextStyle? style;
  final NativeAffineTransform? transform;
  final NativePdfBox? bounds;
  final double? radians;
  final double? centerX;
  final double? centerY;
  final String? label;

  const NativeEditorCommand({
    required this.kind,
    this.objectId,
    this.start,
    this.end,
    this.replacement,
    this.style,
    this.transform,
    this.bounds,
    this.radians,
    this.centerX,
    this.centerY,
    this.label,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      objectId.hashCode ^
      start.hashCode ^
      end.hashCode ^
      replacement.hashCode ^
      style.hashCode ^
      transform.hashCode ^
      bounds.hashCode ^
      radians.hashCode ^
      centerX.hashCode ^
      centerY.hashCode ^
      label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeEditorCommand &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          objectId == other.objectId &&
          start == other.start &&
          end == other.end &&
          replacement == other.replacement &&
          style == other.style &&
          transform == other.transform &&
          bounds == other.bounds &&
          radians == other.radians &&
          centerX == other.centerX &&
          centerY == other.centerY &&
          label == other.label;
}

enum NativeEditorCommandKind {
  replaceTextRange,
  setTextStyle,
  moveObject,
  resizeObject,
  rotateObject,
  createCheckpoint,
  undo,
  redo,
}

class NativeEditorEvent {
  final NativeEditorEventKind kind;
  final String sessionId;
  final BigInt sequence;
  final BigInt? revision;
  final BigInt? latestRevision;
  final NativeCommandResult? result;

  const NativeEditorEvent({
    required this.kind,
    required this.sessionId,
    required this.sequence,
    this.revision,
    this.latestRevision,
    this.result,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      sessionId.hashCode ^
      sequence.hashCode ^
      revision.hashCode ^
      latestRevision.hashCode ^
      result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeEditorEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sessionId == other.sessionId &&
          sequence == other.sequence &&
          revision == other.revision &&
          latestRevision == other.latestRevision &&
          result == other.result;
}

enum NativeEditorEventKind { ready, commandCommitted, lagged, closed }

class NativeEditorMetadata {
  final int schemaVersion;
  final String sessionId;
  final String documentId;
  final String sourceFingerprint;
  final BigInt revision;
  final int pageCount;

  const NativeEditorMetadata({
    required this.schemaVersion,
    required this.sessionId,
    required this.documentId,
    required this.sourceFingerprint,
    required this.revision,
    required this.pageCount,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      sessionId.hashCode ^
      documentId.hashCode ^
      sourceFingerprint.hashCode ^
      revision.hashCode ^
      pageCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeEditorMetadata &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          sessionId == other.sessionId &&
          documentId == other.documentId &&
          sourceFingerprint == other.sourceFingerprint &&
          revision == other.revision &&
          pageCount == other.pageCount;
}

enum NativeEditorSaveMode { save, saveAs }

class NativeEditorSaveRequest {
  final String targetPath;
  final NativeEditorSaveMode mode;
  final NativeSaveAssociation association;
  final String? recoveryDirectory;

  const NativeEditorSaveRequest({
    required this.targetPath,
    required this.mode,
    required this.association,
    this.recoveryDirectory,
  });

  @override
  int get hashCode =>
      targetPath.hashCode ^
      mode.hashCode ^
      association.hashCode ^
      recoveryDirectory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeEditorSaveRequest &&
          runtimeType == other.runtimeType &&
          targetPath == other.targetPath &&
          mode == other.mode &&
          association == other.association &&
          recoveryDirectory == other.recoveryDirectory;
}

class NativeEditorSaveResult {
  final int schemaVersion;
  final String targetPath;
  final BigInt materializedRevision;
  final List<String> completedStages;
  final List<String> warnings;
  final bool followsNewSource;

  const NativeEditorSaveResult({
    required this.schemaVersion,
    required this.targetPath,
    required this.materializedRevision,
    required this.completedStages,
    required this.warnings,
    required this.followsNewSource,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      targetPath.hashCode ^
      materializedRevision.hashCode ^
      completedStages.hashCode ^
      warnings.hashCode ^
      followsNewSource.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeEditorSaveResult &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          targetPath == other.targetPath &&
          materializedRevision == other.materializedRevision &&
          completedStages == other.completedStages &&
          warnings == other.warnings &&
          followsNewSource == other.followsNewSource;
}

class NativeFontFallbackProposal {
  final String token;
  final String fontName;
  final String source;
  final bool embeddingAllowed;
  final String affectedCharacters;

  const NativeFontFallbackProposal({
    required this.token,
    required this.fontName,
    required this.source,
    required this.embeddingAllowed,
    required this.affectedCharacters,
  });

  @override
  int get hashCode =>
      token.hashCode ^
      fontName.hashCode ^
      source.hashCode ^
      embeddingAllowed.hashCode ^
      affectedCharacters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeFontFallbackProposal &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          fontName == other.fontName &&
          source == other.source &&
          embeddingAllowed == other.embeddingAllowed &&
          affectedCharacters == other.affectedCharacters;
}

class NativeFontFallbackProposalRequest {
  final int schemaVersion;
  final BigInt baseRevision;
  final String objectId;
  final int start;
  final int end;
  final String replacement;

  const NativeFontFallbackProposalRequest({
    required this.schemaVersion,
    required this.baseRevision,
    required this.objectId,
    required this.start,
    required this.end,
    required this.replacement,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      baseRevision.hashCode ^
      objectId.hashCode ^
      start.hashCode ^
      end.hashCode ^
      replacement.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeFontFallbackProposalRequest &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          baseRevision == other.baseRevision &&
          objectId == other.objectId &&
          start == other.start &&
          end == other.end &&
          replacement == other.replacement;
}

enum NativeMemoryPressureLevel { moderate, critical }

class NativeObjectDetailsRequest {
  final String objectId;

  const NativeObjectDetailsRequest({required this.objectId});

  @override
  int get hashCode => objectId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeObjectDetailsRequest &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId;
}

class NativeObjectPatch {
  final String objectId;
  final String pageId;
  final BigInt modifiedRevision;
  final String? text;
  final List<NativeTextRun>? textRuns;
  final List<NativeTextCharacterBox>? characterBoxes;
  final NativePdfBox? bounds;
  final NativeAffineTransform? transform;
  final String? fontFingerprint;
  final String? fontAssetHandle;

  const NativeObjectPatch({
    required this.objectId,
    required this.pageId,
    required this.modifiedRevision,
    this.text,
    this.textRuns,
    this.characterBoxes,
    this.bounds,
    this.transform,
    this.fontFingerprint,
    this.fontAssetHandle,
  });

  @override
  int get hashCode =>
      objectId.hashCode ^
      pageId.hashCode ^
      modifiedRevision.hashCode ^
      text.hashCode ^
      textRuns.hashCode ^
      characterBoxes.hashCode ^
      bounds.hashCode ^
      transform.hashCode ^
      fontFingerprint.hashCode ^
      fontAssetHandle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeObjectPatch &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          pageId == other.pageId &&
          modifiedRevision == other.modifiedRevision &&
          text == other.text &&
          textRuns == other.textRuns &&
          characterBoxes == other.characterBoxes &&
          bounds == other.bounds &&
          transform == other.transform &&
          fontFingerprint == other.fontFingerprint &&
          fontAssetHandle == other.fontAssetHandle;
}

class NativeOpenEditorRequest {
  final String sourcePath;
  final String? projectRoot;

  const NativeOpenEditorRequest({required this.sourcePath, this.projectRoot});

  @override
  int get hashCode => sourcePath.hashCode ^ projectRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeOpenEditorRequest &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          projectRoot == other.projectRoot;
}

class NativePageScene {
  final int schemaVersion;
  final String pageId;
  final int pageNumber;
  final double width;
  final double height;
  final BigInt revision;
  final List<NativeSceneObject> objects;

  const NativePageScene({
    required this.schemaVersion,
    required this.pageId,
    required this.pageNumber,
    required this.width,
    required this.height,
    required this.revision,
    required this.objects,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      pageId.hashCode ^
      pageNumber.hashCode ^
      width.hashCode ^
      height.hashCode ^
      revision.hashCode ^
      objects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativePageScene &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          pageId == other.pageId &&
          pageNumber == other.pageNumber &&
          width == other.width &&
          height == other.height &&
          revision == other.revision &&
          objects == other.objects;
}

class NativePageSceneRequest {
  final int pageNumber;
  final BigInt expectedRevision;
  final NativeViewportPriority priority;

  const NativePageSceneRequest({
    required this.pageNumber,
    required this.expectedRevision,
    required this.priority,
  });

  @override
  int get hashCode =>
      pageNumber.hashCode ^ expectedRevision.hashCode ^ priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativePageSceneRequest &&
          runtimeType == other.runtimeType &&
          pageNumber == other.pageNumber &&
          expectedRevision == other.expectedRevision &&
          priority == other.priority;
}

class NativePdfBox {
  final double left;
  final double bottom;
  final double right;
  final double top;

  const NativePdfBox({
    required this.left,
    required this.bottom,
    required this.right,
    required this.top,
  });

  @override
  int get hashCode =>
      left.hashCode ^ bottom.hashCode ^ right.hashCode ^ top.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativePdfBox &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          bottom == other.bottom &&
          right == other.right &&
          top == other.top;
}

class NativePhysicalLocator {
  final int pageNumber;
  final Uint32List objectPath;
  final String objectType;
  final String sourceFingerprint;
  final BigInt objectRevision;

  const NativePhysicalLocator({
    required this.pageNumber,
    required this.objectPath,
    required this.objectType,
    required this.sourceFingerprint,
    required this.objectRevision,
  });

  @override
  int get hashCode =>
      pageNumber.hashCode ^
      objectPath.hashCode ^
      objectType.hashCode ^
      sourceFingerprint.hashCode ^
      objectRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativePhysicalLocator &&
          runtimeType == other.runtimeType &&
          pageNumber == other.pageNumber &&
          objectPath == other.objectPath &&
          objectType == other.objectType &&
          sourceFingerprint == other.sourceFingerprint &&
          objectRevision == other.objectRevision;
}

enum NativeSaveAssociation { keepOriginalAssociation, followNewSource }

class NativeSceneObject {
  final NativeSceneObjectKind kind;
  final String objectId;
  final String pageId;
  final String? text;
  final NativePdfBox bounds;
  final NativeAffineTransform transform;
  final String capability;
  final String? capabilityReason;
  final BigInt modifiedRevision;
  final List<NativeTextRun> runs;
  final List<NativeTextCharacterBox> characterBoxes;
  final NativeTextLayoutRecipe? layout;
  final String? fontFingerprint;
  final String? fontAssetHandle;

  /// Populated only by the live PDFium backend. Legacy adapter scenes do
  /// not have a physical PDFium object path and must remain explicit about
  /// that absence.
  final NativePhysicalLocator? physicalLocator;

  const NativeSceneObject({
    required this.kind,
    required this.objectId,
    required this.pageId,
    this.text,
    required this.bounds,
    required this.transform,
    required this.capability,
    this.capabilityReason,
    required this.modifiedRevision,
    required this.runs,
    required this.characterBoxes,
    this.layout,
    this.fontFingerprint,
    this.fontAssetHandle,
    this.physicalLocator,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      objectId.hashCode ^
      pageId.hashCode ^
      text.hashCode ^
      bounds.hashCode ^
      transform.hashCode ^
      capability.hashCode ^
      capabilityReason.hashCode ^
      modifiedRevision.hashCode ^
      runs.hashCode ^
      characterBoxes.hashCode ^
      layout.hashCode ^
      fontFingerprint.hashCode ^
      fontAssetHandle.hashCode ^
      physicalLocator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSceneObject &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          objectId == other.objectId &&
          pageId == other.pageId &&
          text == other.text &&
          bounds == other.bounds &&
          transform == other.transform &&
          capability == other.capability &&
          capabilityReason == other.capabilityReason &&
          modifiedRevision == other.modifiedRevision &&
          runs == other.runs &&
          characterBoxes == other.characterBoxes &&
          layout == other.layout &&
          fontFingerprint == other.fontFingerprint &&
          fontAssetHandle == other.fontAssetHandle &&
          physicalLocator == other.physicalLocator;
}

enum NativeSceneObjectKind { text, unsupported }

class NativeSearchMatch {
  final String objectId;
  final String pageId;
  final int pageNumber;
  final int startUtf16;
  final int endUtf16;
  final String quotedText;

  const NativeSearchMatch({
    required this.objectId,
    required this.pageId,
    required this.pageNumber,
    required this.startUtf16,
    required this.endUtf16,
    required this.quotedText,
  });

  @override
  int get hashCode =>
      objectId.hashCode ^
      pageId.hashCode ^
      pageNumber.hashCode ^
      startUtf16.hashCode ^
      endUtf16.hashCode ^
      quotedText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSearchMatch &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          pageId == other.pageId &&
          pageNumber == other.pageNumber &&
          startUtf16 == other.startUtf16 &&
          endUtf16 == other.endUtf16 &&
          quotedText == other.quotedText;
}

enum NativeSearchMode { exact, caseFolded, normalized, regex }

class NativeSearchRequest {
  final BigInt expectedRevision;
  final String query;
  final NativeSearchMode mode;
  final bool wholeWord;
  final int offset;
  final int limit;

  const NativeSearchRequest({
    required this.expectedRevision,
    required this.query,
    required this.mode,
    required this.wholeWord,
    required this.offset,
    required this.limit,
  });

  @override
  int get hashCode =>
      expectedRevision.hashCode ^
      query.hashCode ^
      mode.hashCode ^
      wholeWord.hashCode ^
      offset.hashCode ^
      limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSearchRequest &&
          runtimeType == other.runtimeType &&
          expectedRevision == other.expectedRevision &&
          query == other.query &&
          mode == other.mode &&
          wholeWord == other.wholeWord &&
          offset == other.offset &&
          limit == other.limit;
}

class NativeSearchResult {
  final int schemaVersion;
  final BigInt revision;
  final List<NativeSearchMatch> matches;
  final int totalMatches;
  final int indexedPages;
  final int pageCount;
  final bool isComplete;

  const NativeSearchResult({
    required this.schemaVersion,
    required this.revision,
    required this.matches,
    required this.totalMatches,
    required this.indexedPages,
    required this.pageCount,
    required this.isComplete,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      revision.hashCode ^
      matches.hashCode ^
      totalMatches.hashCode ^
      indexedPages.hashCode ^
      pageCount.hashCode ^
      isComplete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSearchResult &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          revision == other.revision &&
          matches == other.matches &&
          totalMatches == other.totalMatches &&
          indexedPages == other.indexedPages &&
          pageCount == other.pageCount &&
          isComplete == other.isComplete;
}

enum NativeSelectionKind { textRanges, objects }

class NativeSelectionRange {
  final String objectId;
  final String pageId;
  final int pageNumber;
  final int startUtf16;
  final int endUtf16;
  final String quotedText;

  const NativeSelectionRange({
    required this.objectId,
    required this.pageId,
    required this.pageNumber,
    required this.startUtf16,
    required this.endUtf16,
    required this.quotedText,
  });

  @override
  int get hashCode =>
      objectId.hashCode ^
      pageId.hashCode ^
      pageNumber.hashCode ^
      startUtf16.hashCode ^
      endUtf16.hashCode ^
      quotedText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSelectionRange &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          pageId == other.pageId &&
          pageNumber == other.pageNumber &&
          startUtf16 == other.startUtf16 &&
          endUtf16 == other.endUtf16 &&
          quotedText == other.quotedText;
}

class NativeSelectionRebase {
  final String objectId;
  final int start;
  final int end;
  final int insertedUtf16Length;

  const NativeSelectionRebase({
    required this.objectId,
    required this.start,
    required this.end,
    required this.insertedUtf16Length,
  });

  @override
  int get hashCode =>
      objectId.hashCode ^
      start.hashCode ^
      end.hashCode ^
      insertedUtf16Length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSelectionRebase &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          start == other.start &&
          end == other.end &&
          insertedUtf16Length == other.insertedUtf16Length;
}

class NativeSelectionSet {
  final BigInt expectedRevision;
  final NativeSelectionKind kind;
  final List<NativeSelectionRange> ranges;
  final List<String> objectIds;
  final int? primaryIndex;

  const NativeSelectionSet({
    required this.expectedRevision,
    required this.kind,
    required this.ranges,
    required this.objectIds,
    this.primaryIndex,
  });

  @override
  int get hashCode =>
      expectedRevision.hashCode ^
      kind.hashCode ^
      ranges.hashCode ^
      objectIds.hashCode ^
      primaryIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSelectionSet &&
          runtimeType == other.runtimeType &&
          expectedRevision == other.expectedRevision &&
          kind == other.kind &&
          ranges == other.ranges &&
          objectIds == other.objectIds &&
          primaryIndex == other.primaryIndex;
}

class NativeSubmitCommandRequest {
  final int schemaVersion;
  final String commandId;
  final BigInt baseRevision;
  final NativeEditorCommand payload;

  const NativeSubmitCommandRequest({
    required this.schemaVersion,
    required this.commandId,
    required this.baseRevision,
    required this.payload,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      commandId.hashCode ^
      baseRevision.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSubmitCommandRequest &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          commandId == other.commandId &&
          baseRevision == other.baseRevision &&
          payload == other.payload;
}

class NativeTextCharacterBox {
  final int start;
  final int end;
  final NativePdfBox bounds;

  const NativeTextCharacterBox({
    required this.start,
    required this.end,
    required this.bounds,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ bounds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeTextCharacterBox &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          bounds == other.bounds;
}

class NativeTextLayoutRecipe {
  final double baseline;
  final double lineHeight;
  final double characterSpacing;
  final double horizontalScale;
  final String direction;

  const NativeTextLayoutRecipe({
    required this.baseline,
    required this.lineHeight,
    required this.characterSpacing,
    required this.horizontalScale,
    required this.direction,
  });

  @override
  int get hashCode =>
      baseline.hashCode ^
      lineHeight.hashCode ^
      characterSpacing.hashCode ^
      horizontalScale.hashCode ^
      direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeTextLayoutRecipe &&
          runtimeType == other.runtimeType &&
          baseline == other.baseline &&
          lineHeight == other.lineHeight &&
          characterSpacing == other.characterSpacing &&
          horizontalScale == other.horizontalScale &&
          direction == other.direction;
}

class NativeTextRun {
  final int start;
  final int end;
  final NativeTextStyle style;

  const NativeTextRun({
    required this.start,
    required this.end,
    required this.style,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ style.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeTextRun &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          style == other.style;
}

class NativeTextStyle {
  final String? fontFamily;
  final double fontSize;
  final int fontWeight;
  final bool italic;
  final Uint8List colorRgba;

  const NativeTextStyle({
    this.fontFamily,
    required this.fontSize,
    required this.fontWeight,
    required this.italic,
    required this.colorRgba,
  });

  @override
  int get hashCode =>
      fontFamily.hashCode ^
      fontSize.hashCode ^
      fontWeight.hashCode ^
      italic.hashCode ^
      colorRgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeTextStyle &&
          runtimeType == other.runtimeType &&
          fontFamily == other.fontFamily &&
          fontSize == other.fontSize &&
          fontWeight == other.fontWeight &&
          italic == other.italic &&
          colorRgba == other.colorRgba;
}

class NativeValidatedSelection {
  final int schemaVersion;
  final BigInt revision;
  final NativeSelectionKind kind;
  final List<NativeSelectionRange> ranges;
  final List<String> objectIds;
  final int? primaryIndex;

  const NativeValidatedSelection({
    required this.schemaVersion,
    required this.revision,
    required this.kind,
    required this.ranges,
    required this.objectIds,
    this.primaryIndex,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      revision.hashCode ^
      kind.hashCode ^
      ranges.hashCode ^
      objectIds.hashCode ^
      primaryIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeValidatedSelection &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          revision == other.revision &&
          kind == other.kind &&
          ranges == other.ranges &&
          objectIds == other.objectIds &&
          primaryIndex == other.primaryIndex;
}

enum NativeViewportPriority { background, preload, visible, activeSelection }
