// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `adapter_error`, `affine_transform`, `editing_error`, `editor_command`, `native_box`, `native_command_result`, `native_event`, `native_object_patch`, `native_scene_object`, `native_text_run`, `native_transform`, `parse_object_id`, `pdf_box`, `required`, `text_style`, `viewport_priority`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativeEditorSession>>
abstract class NativeEditorSession implements RustOpaqueInterface {
  Future<NativeCommandResult> checkpoint({
    required NativeCheckpointRequest request,
  });

  Future<NativeCleanPatchAsset> cleanPatch({
    required NativeCleanPatchRequest request,
  });

  Future<void> close();

  Stream<NativeEditorEvent> events();

  Future<NativeEditorMetadata> metadata();

  Future<NativeSceneObject> objectDetails({
    required NativeObjectDetailsRequest request,
  });

  static Future<NativeEditorSession> open({
    required NativeOpenEditorRequest request,
  }) => RustLib.instance.api.crateEditingApiNativeEditorSessionOpen(
    request: request,
  );

  Future<NativePageScene> pageScene({required NativePageSceneRequest request});

  Future<void> releaseCleanPatchMemory();

  Future<NativeCommandResult> submit({
    required NativeSubmitCommandRequest request,
  });
}

class NativeAffineTransform {
  final double a;
  final double b;
  final double c;
  final double d;
  final double e;
  final double f;

  const NativeAffineTransform({
    required this.a,
    required this.b,
    required this.c,
    required this.d,
    required this.e,
    required this.f,
  });

  @override
  int get hashCode =>
      a.hashCode ^
      b.hashCode ^
      c.hashCode ^
      d.hashCode ^
      e.hashCode ^
      f.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeAffineTransform &&
          runtimeType == other.runtimeType &&
          a == other.a &&
          b == other.b &&
          c == other.c &&
          d == other.d &&
          e == other.e &&
          f == other.f;
}

class NativeCheckpointRequest {
  final BigInt baseRevision;
  final String label;

  const NativeCheckpointRequest({
    required this.baseRevision,
    required this.label,
  });

  @override
  int get hashCode => baseRevision.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeCheckpointRequest &&
          runtimeType == other.runtimeType &&
          baseRevision == other.baseRevision &&
          label == other.label;
}

class NativeCleanPatchAsset {
  final String handle;
  final String objectId;
  final NativePdfBox bounds;
  final int dpi;
  final int width;
  final int height;
  final Uint8List rgbaBytes;
  final double bleedPoints;

  const NativeCleanPatchAsset({
    required this.handle,
    required this.objectId,
    required this.bounds,
    required this.dpi,
    required this.width,
    required this.height,
    required this.rgbaBytes,
    required this.bleedPoints,
  });

  @override
  int get hashCode =>
      handle.hashCode ^
      objectId.hashCode ^
      bounds.hashCode ^
      dpi.hashCode ^
      width.hashCode ^
      height.hashCode ^
      rgbaBytes.hashCode ^
      bleedPoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeCleanPatchAsset &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          objectId == other.objectId &&
          bounds == other.bounds &&
          dpi == other.dpi &&
          width == other.width &&
          height == other.height &&
          rgbaBytes == other.rgbaBytes &&
          bleedPoints == other.bleedPoints;
}

class NativeCleanPatchRequest {
  final String objectId;
  final int dpi;

  const NativeCleanPatchRequest({required this.objectId, required this.dpi});

  @override
  int get hashCode => objectId.hashCode ^ dpi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeCleanPatchRequest &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          dpi == other.dpi;
}

class NativeCommandResult {
  final String commandId;
  final BigInt previousRevision;
  final BigInt committedRevision;
  final bool durable;
  final List<String> warnings;
  final NativeSelectionRebase? selectionRebase;
  final List<NativeObjectPatch> objectPatches;

  const NativeCommandResult({
    required this.commandId,
    required this.previousRevision,
    required this.committedRevision,
    required this.durable,
    required this.warnings,
    this.selectionRebase,
    required this.objectPatches,
  });

  @override
  int get hashCode =>
      commandId.hashCode ^
      previousRevision.hashCode ^
      committedRevision.hashCode ^
      durable.hashCode ^
      warnings.hashCode ^
      selectionRebase.hashCode ^
      objectPatches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeCommandResult &&
          runtimeType == other.runtimeType &&
          commandId == other.commandId &&
          previousRevision == other.previousRevision &&
          committedRevision == other.committedRevision &&
          durable == other.durable &&
          warnings == other.warnings &&
          selectionRebase == other.selectionRebase &&
          objectPatches == other.objectPatches;
}

class NativeEditorCommand {
  final NativeEditorCommandKind kind;
  final String? objectId;
  final int? start;
  final int? end;
  final String? replacement;
  final NativeTextStyle? style;
  final NativeAffineTransform? transform;
  final NativePdfBox? bounds;
  final double? radians;
  final double? centerX;
  final double? centerY;
  final String? label;

  const NativeEditorCommand({
    required this.kind,
    this.objectId,
    this.start,
    this.end,
    this.replacement,
    this.style,
    this.transform,
    this.bounds,
    this.radians,
    this.centerX,
    this.centerY,
    this.label,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      objectId.hashCode ^
      start.hashCode ^
      end.hashCode ^
      replacement.hashCode ^
      style.hashCode ^
      transform.hashCode ^
      bounds.hashCode ^
      radians.hashCode ^
      centerX.hashCode ^
      centerY.hashCode ^
      label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeEditorCommand &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          objectId == other.objectId &&
          start == other.start &&
          end == other.end &&
          replacement == other.replacement &&
          style == other.style &&
          transform == other.transform &&
          bounds == other.bounds &&
          radians == other.radians &&
          centerX == other.centerX &&
          centerY == other.centerY &&
          label == other.label;
}

enum NativeEditorCommandKind {
  replaceTextRange,
  setTextStyle,
  moveObject,
  resizeObject,
  rotateObject,
  createCheckpoint,
  undo,
  redo,
}

class NativeEditorEvent {
  final NativeEditorEventKind kind;
  final String sessionId;
  final BigInt sequence;
  final BigInt? revision;
  final BigInt? latestRevision;
  final NativeCommandResult? result;

  const NativeEditorEvent({
    required this.kind,
    required this.sessionId,
    required this.sequence,
    this.revision,
    this.latestRevision,
    this.result,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      sessionId.hashCode ^
      sequence.hashCode ^
      revision.hashCode ^
      latestRevision.hashCode ^
      result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeEditorEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sessionId == other.sessionId &&
          sequence == other.sequence &&
          revision == other.revision &&
          latestRevision == other.latestRevision &&
          result == other.result;
}

enum NativeEditorEventKind { ready, commandCommitted, lagged, closed }

class NativeEditorMetadata {
  final int schemaVersion;
  final String sessionId;
  final String documentId;
  final String sourceFingerprint;
  final BigInt revision;
  final int pageCount;

  const NativeEditorMetadata({
    required this.schemaVersion,
    required this.sessionId,
    required this.documentId,
    required this.sourceFingerprint,
    required this.revision,
    required this.pageCount,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      sessionId.hashCode ^
      documentId.hashCode ^
      sourceFingerprint.hashCode ^
      revision.hashCode ^
      pageCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeEditorMetadata &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          sessionId == other.sessionId &&
          documentId == other.documentId &&
          sourceFingerprint == other.sourceFingerprint &&
          revision == other.revision &&
          pageCount == other.pageCount;
}

class NativeObjectDetailsRequest {
  final String objectId;

  const NativeObjectDetailsRequest({required this.objectId});

  @override
  int get hashCode => objectId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeObjectDetailsRequest &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId;
}

class NativeObjectPatch {
  final String objectId;
  final String pageId;
  final BigInt modifiedRevision;
  final String? text;
  final List<NativeTextRun>? textRuns;
  final NativePdfBox? bounds;
  final NativeAffineTransform? transform;

  const NativeObjectPatch({
    required this.objectId,
    required this.pageId,
    required this.modifiedRevision,
    this.text,
    this.textRuns,
    this.bounds,
    this.transform,
  });

  @override
  int get hashCode =>
      objectId.hashCode ^
      pageId.hashCode ^
      modifiedRevision.hashCode ^
      text.hashCode ^
      textRuns.hashCode ^
      bounds.hashCode ^
      transform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeObjectPatch &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          pageId == other.pageId &&
          modifiedRevision == other.modifiedRevision &&
          text == other.text &&
          textRuns == other.textRuns &&
          bounds == other.bounds &&
          transform == other.transform;
}

class NativeOpenEditorRequest {
  final String sourcePath;
  final String? projectRoot;

  const NativeOpenEditorRequest({required this.sourcePath, this.projectRoot});

  @override
  int get hashCode => sourcePath.hashCode ^ projectRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeOpenEditorRequest &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          projectRoot == other.projectRoot;
}

class NativePageScene {
  final int schemaVersion;
  final String pageId;
  final int pageNumber;
  final double width;
  final double height;
  final BigInt revision;
  final List<NativeSceneObject> objects;

  const NativePageScene({
    required this.schemaVersion,
    required this.pageId,
    required this.pageNumber,
    required this.width,
    required this.height,
    required this.revision,
    required this.objects,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      pageId.hashCode ^
      pageNumber.hashCode ^
      width.hashCode ^
      height.hashCode ^
      revision.hashCode ^
      objects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativePageScene &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          pageId == other.pageId &&
          pageNumber == other.pageNumber &&
          width == other.width &&
          height == other.height &&
          revision == other.revision &&
          objects == other.objects;
}

class NativePageSceneRequest {
  final int pageNumber;
  final BigInt expectedRevision;
  final NativeViewportPriority priority;

  const NativePageSceneRequest({
    required this.pageNumber,
    required this.expectedRevision,
    required this.priority,
  });

  @override
  int get hashCode =>
      pageNumber.hashCode ^ expectedRevision.hashCode ^ priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativePageSceneRequest &&
          runtimeType == other.runtimeType &&
          pageNumber == other.pageNumber &&
          expectedRevision == other.expectedRevision &&
          priority == other.priority;
}

class NativePdfBox {
  final double left;
  final double bottom;
  final double right;
  final double top;

  const NativePdfBox({
    required this.left,
    required this.bottom,
    required this.right,
    required this.top,
  });

  @override
  int get hashCode =>
      left.hashCode ^ bottom.hashCode ^ right.hashCode ^ top.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativePdfBox &&
          runtimeType == other.runtimeType &&
          left == other.left &&
          bottom == other.bottom &&
          right == other.right &&
          top == other.top;
}

class NativeSceneObject {
  final NativeSceneObjectKind kind;
  final String objectId;
  final String pageId;
  final String? text;
  final NativePdfBox bounds;
  final NativeAffineTransform transform;
  final String capability;
  final String? capabilityReason;
  final BigInt modifiedRevision;
  final List<NativeTextRun> runs;
  final NativeTextLayoutRecipe? layout;
  final String? fontFingerprint;
  final String? fontAssetHandle;

  const NativeSceneObject({
    required this.kind,
    required this.objectId,
    required this.pageId,
    this.text,
    required this.bounds,
    required this.transform,
    required this.capability,
    this.capabilityReason,
    required this.modifiedRevision,
    required this.runs,
    this.layout,
    this.fontFingerprint,
    this.fontAssetHandle,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      objectId.hashCode ^
      pageId.hashCode ^
      text.hashCode ^
      bounds.hashCode ^
      transform.hashCode ^
      capability.hashCode ^
      capabilityReason.hashCode ^
      modifiedRevision.hashCode ^
      runs.hashCode ^
      layout.hashCode ^
      fontFingerprint.hashCode ^
      fontAssetHandle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSceneObject &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          objectId == other.objectId &&
          pageId == other.pageId &&
          text == other.text &&
          bounds == other.bounds &&
          transform == other.transform &&
          capability == other.capability &&
          capabilityReason == other.capabilityReason &&
          modifiedRevision == other.modifiedRevision &&
          runs == other.runs &&
          layout == other.layout &&
          fontFingerprint == other.fontFingerprint &&
          fontAssetHandle == other.fontAssetHandle;
}

enum NativeSceneObjectKind { text, unsupported }

class NativeSelectionRebase {
  final String objectId;
  final int start;
  final int end;
  final int insertedUtf16Length;

  const NativeSelectionRebase({
    required this.objectId,
    required this.start,
    required this.end,
    required this.insertedUtf16Length,
  });

  @override
  int get hashCode =>
      objectId.hashCode ^
      start.hashCode ^
      end.hashCode ^
      insertedUtf16Length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSelectionRebase &&
          runtimeType == other.runtimeType &&
          objectId == other.objectId &&
          start == other.start &&
          end == other.end &&
          insertedUtf16Length == other.insertedUtf16Length;
}

class NativeSubmitCommandRequest {
  final int schemaVersion;
  final String commandId;
  final BigInt baseRevision;
  final NativeEditorCommand payload;

  const NativeSubmitCommandRequest({
    required this.schemaVersion,
    required this.commandId,
    required this.baseRevision,
    required this.payload,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      commandId.hashCode ^
      baseRevision.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSubmitCommandRequest &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          commandId == other.commandId &&
          baseRevision == other.baseRevision &&
          payload == other.payload;
}

class NativeTextLayoutRecipe {
  final double baseline;
  final double lineHeight;
  final double characterSpacing;
  final double horizontalScale;
  final String direction;

  const NativeTextLayoutRecipe({
    required this.baseline,
    required this.lineHeight,
    required this.characterSpacing,
    required this.horizontalScale,
    required this.direction,
  });

  @override
  int get hashCode =>
      baseline.hashCode ^
      lineHeight.hashCode ^
      characterSpacing.hashCode ^
      horizontalScale.hashCode ^
      direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeTextLayoutRecipe &&
          runtimeType == other.runtimeType &&
          baseline == other.baseline &&
          lineHeight == other.lineHeight &&
          characterSpacing == other.characterSpacing &&
          horizontalScale == other.horizontalScale &&
          direction == other.direction;
}

class NativeTextRun {
  final int start;
  final int end;
  final NativeTextStyle style;

  const NativeTextRun({
    required this.start,
    required this.end,
    required this.style,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ style.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeTextRun &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          style == other.style;
}

class NativeTextStyle {
  final String? fontFamily;
  final double fontSize;
  final int fontWeight;
  final bool italic;
  final Uint8List colorRgba;

  const NativeTextStyle({
    this.fontFamily,
    required this.fontSize,
    required this.fontWeight,
    required this.italic,
    required this.colorRgba,
  });

  @override
  int get hashCode =>
      fontFamily.hashCode ^
      fontSize.hashCode ^
      fontWeight.hashCode ^
      italic.hashCode ^
      colorRgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeTextStyle &&
          runtimeType == other.runtimeType &&
          fontFamily == other.fontFamily &&
          fontSize == other.fontSize &&
          fontWeight == other.fontWeight &&
          italic == other.italic &&
          colorRgba == other.colorRgba;
}

enum NativeViewportPriority { background, preload, visible, activeSelection }
