// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'editing_api.dart';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NativeEditorSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NativePdfSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  NativeEditorSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    dynamic raw,
  );

  @protected
  NativePdfSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  );

  @protected
  NativePdfSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  );

  @protected
  NativeEditorSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    dynamic raw,
  );

  @protected
  NativePdfSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  );

  @protected
  NativeEditorSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    dynamic raw,
  );

  @protected
  NativePdfSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  );

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<NativeEditorEvent>
  dco_decode_StreamSink_native_editor_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  NativeAffineTransform dco_decode_box_autoadd_native_affine_transform(
    dynamic raw,
  );

  @protected
  NativeCommandResult dco_decode_box_autoadd_native_command_result(dynamic raw);

  @protected
  NativeOpenEditorRequest dco_decode_box_autoadd_native_open_editor_request(
    dynamic raw,
  );

  @protected
  NativePageSceneRequest dco_decode_box_autoadd_native_page_scene_request(
    dynamic raw,
  );

  @protected
  NativePdfBox dco_decode_box_autoadd_native_pdf_box(dynamic raw);

  @protected
  NativePdfComposeRequest dco_decode_box_autoadd_native_pdf_compose_request(
    dynamic raw,
  );

  @protected
  NativePdfSaveRequest dco_decode_box_autoadd_native_pdf_save_request(
    dynamic raw,
  );

  @protected
  NativeRagIndexRequest dco_decode_box_autoadd_native_rag_index_request(
    dynamic raw,
  );

  @protected
  NativeRagQueryRequest dco_decode_box_autoadd_native_rag_query_request(
    dynamic raw,
  );

  @protected
  NativeSubmitCommandRequest
  dco_decode_box_autoadd_native_submit_command_request(dynamic raw);

  @protected
  NativeTextStyle dco_decode_box_autoadd_native_text_style(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<NativeObjectPatch> dco_decode_list_native_object_patch(dynamic raw);

  @protected
  List<NativePdfBookmark> dco_decode_list_native_pdf_bookmark(dynamic raw);

  @protected
  List<NativePdfHighlight> dco_decode_list_native_pdf_highlight(dynamic raw);

  @protected
  List<NativePdfSource> dco_decode_list_native_pdf_source(dynamic raw);

  @protected
  List<NativeRagChunk> dco_decode_list_native_rag_chunk(dynamic raw);

  @protected
  List<NativeRagQueryResult> dco_decode_list_native_rag_query_result(
    dynamic raw,
  );

  @protected
  List<NativeSceneObject> dco_decode_list_native_scene_object(dynamic raw);

  @protected
  List<NativeTextRun> dco_decode_list_native_text_run(dynamic raw);

  @protected
  List<PdfSearchMatch> dco_decode_list_pdf_search_match(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw);

  @protected
  NativeAffineTransform dco_decode_native_affine_transform(dynamic raw);

  @protected
  NativeCommandResult dco_decode_native_command_result(dynamic raw);

  @protected
  NativeEditorCommand dco_decode_native_editor_command(dynamic raw);

  @protected
  NativeEditorCommandKind dco_decode_native_editor_command_kind(dynamic raw);

  @protected
  NativeEditorEvent dco_decode_native_editor_event(dynamic raw);

  @protected
  NativeEditorEventKind dco_decode_native_editor_event_kind(dynamic raw);

  @protected
  NativeEditorMetadata dco_decode_native_editor_metadata(dynamic raw);

  @protected
  NativeObjectPatch dco_decode_native_object_patch(dynamic raw);

  @protected
  NativeOpenEditorRequest dco_decode_native_open_editor_request(dynamic raw);

  @protected
  NativePageScene dco_decode_native_page_scene(dynamic raw);

  @protected
  NativePageSceneRequest dco_decode_native_page_scene_request(dynamic raw);

  @protected
  NativePdfAnnotations dco_decode_native_pdf_annotations(dynamic raw);

  @protected
  NativePdfBookmark dco_decode_native_pdf_bookmark(dynamic raw);

  @protected
  NativePdfBox dco_decode_native_pdf_box(dynamic raw);

  @protected
  NativePdfComposeRequest dco_decode_native_pdf_compose_request(dynamic raw);

  @protected
  NativePdfComposeResponse dco_decode_native_pdf_compose_response(dynamic raw);

  @protected
  NativePdfHighlight dco_decode_native_pdf_highlight(dynamic raw);

  @protected
  NativePdfSaveRequest dco_decode_native_pdf_save_request(dynamic raw);

  @protected
  NativePdfSource dco_decode_native_pdf_source(dynamic raw);

  @protected
  NativeRagChunk dco_decode_native_rag_chunk(dynamic raw);

  @protected
  NativeRagIndexRequest dco_decode_native_rag_index_request(dynamic raw);

  @protected
  NativeRagIndexResponse dco_decode_native_rag_index_response(dynamic raw);

  @protected
  NativeRagQueryRequest dco_decode_native_rag_query_request(dynamic raw);

  @protected
  NativeRagQueryResponse dco_decode_native_rag_query_response(dynamic raw);

  @protected
  NativeRagQueryResult dco_decode_native_rag_query_result(dynamic raw);

  @protected
  NativeSceneObject dco_decode_native_scene_object(dynamic raw);

  @protected
  NativeSceneObjectKind dco_decode_native_scene_object_kind(dynamic raw);

  @protected
  NativeSubmitCommandRequest dco_decode_native_submit_command_request(
    dynamic raw,
  );

  @protected
  NativeTextRun dco_decode_native_text_run(dynamic raw);

  @protected
  NativeTextStyle dco_decode_native_text_style(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  NativeAffineTransform? dco_decode_opt_box_autoadd_native_affine_transform(
    dynamic raw,
  );

  @protected
  NativeCommandResult? dco_decode_opt_box_autoadd_native_command_result(
    dynamic raw,
  );

  @protected
  NativePdfBox? dco_decode_opt_box_autoadd_native_pdf_box(dynamic raw);

  @protected
  NativeTextStyle? dco_decode_opt_box_autoadd_native_text_style(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<NativeTextRun>? dco_decode_opt_list_native_text_run(dynamic raw);

  @protected
  PdfDocumentMetadata dco_decode_pdf_document_metadata(dynamic raw);

  @protected
  PdfSearchMatch dco_decode_pdf_search_match(dynamic raw);

  @protected
  (double, double, double, double) dco_decode_record_f_32_f_32_f_32_f_32(
    dynamic raw,
  );

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  NativeEditorSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  );

  @protected
  NativeEditorSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  );

  @protected
  NativeEditorSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<NativeEditorEvent>
  sse_decode_StreamSink_native_editor_event_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  NativeAffineTransform sse_decode_box_autoadd_native_affine_transform(
    SseDeserializer deserializer,
  );

  @protected
  NativeCommandResult sse_decode_box_autoadd_native_command_result(
    SseDeserializer deserializer,
  );

  @protected
  NativeOpenEditorRequest sse_decode_box_autoadd_native_open_editor_request(
    SseDeserializer deserializer,
  );

  @protected
  NativePageSceneRequest sse_decode_box_autoadd_native_page_scene_request(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfBox sse_decode_box_autoadd_native_pdf_box(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfComposeRequest sse_decode_box_autoadd_native_pdf_compose_request(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfSaveRequest sse_decode_box_autoadd_native_pdf_save_request(
    SseDeserializer deserializer,
  );

  @protected
  NativeRagIndexRequest sse_decode_box_autoadd_native_rag_index_request(
    SseDeserializer deserializer,
  );

  @protected
  NativeRagQueryRequest sse_decode_box_autoadd_native_rag_query_request(
    SseDeserializer deserializer,
  );

  @protected
  NativeSubmitCommandRequest
  sse_decode_box_autoadd_native_submit_command_request(
    SseDeserializer deserializer,
  );

  @protected
  NativeTextStyle sse_decode_box_autoadd_native_text_style(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<NativeObjectPatch> sse_decode_list_native_object_patch(
    SseDeserializer deserializer,
  );

  @protected
  List<NativePdfBookmark> sse_decode_list_native_pdf_bookmark(
    SseDeserializer deserializer,
  );

  @protected
  List<NativePdfHighlight> sse_decode_list_native_pdf_highlight(
    SseDeserializer deserializer,
  );

  @protected
  List<NativePdfSource> sse_decode_list_native_pdf_source(
    SseDeserializer deserializer,
  );

  @protected
  List<NativeRagChunk> sse_decode_list_native_rag_chunk(
    SseDeserializer deserializer,
  );

  @protected
  List<NativeRagQueryResult> sse_decode_list_native_rag_query_result(
    SseDeserializer deserializer,
  );

  @protected
  List<NativeSceneObject> sse_decode_list_native_scene_object(
    SseDeserializer deserializer,
  );

  @protected
  List<NativeTextRun> sse_decode_list_native_text_run(
    SseDeserializer deserializer,
  );

  @protected
  List<PdfSearchMatch> sse_decode_list_pdf_search_match(
    SseDeserializer deserializer,
  );

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer);

  @protected
  NativeAffineTransform sse_decode_native_affine_transform(
    SseDeserializer deserializer,
  );

  @protected
  NativeCommandResult sse_decode_native_command_result(
    SseDeserializer deserializer,
  );

  @protected
  NativeEditorCommand sse_decode_native_editor_command(
    SseDeserializer deserializer,
  );

  @protected
  NativeEditorCommandKind sse_decode_native_editor_command_kind(
    SseDeserializer deserializer,
  );

  @protected
  NativeEditorEvent sse_decode_native_editor_event(
    SseDeserializer deserializer,
  );

  @protected
  NativeEditorEventKind sse_decode_native_editor_event_kind(
    SseDeserializer deserializer,
  );

  @protected
  NativeEditorMetadata sse_decode_native_editor_metadata(
    SseDeserializer deserializer,
  );

  @protected
  NativeObjectPatch sse_decode_native_object_patch(
    SseDeserializer deserializer,
  );

  @protected
  NativeOpenEditorRequest sse_decode_native_open_editor_request(
    SseDeserializer deserializer,
  );

  @protected
  NativePageScene sse_decode_native_page_scene(SseDeserializer deserializer);

  @protected
  NativePageSceneRequest sse_decode_native_page_scene_request(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfAnnotations sse_decode_native_pdf_annotations(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfBookmark sse_decode_native_pdf_bookmark(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfBox sse_decode_native_pdf_box(SseDeserializer deserializer);

  @protected
  NativePdfComposeRequest sse_decode_native_pdf_compose_request(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfComposeResponse sse_decode_native_pdf_compose_response(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfHighlight sse_decode_native_pdf_highlight(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfSaveRequest sse_decode_native_pdf_save_request(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfSource sse_decode_native_pdf_source(SseDeserializer deserializer);

  @protected
  NativeRagChunk sse_decode_native_rag_chunk(SseDeserializer deserializer);

  @protected
  NativeRagIndexRequest sse_decode_native_rag_index_request(
    SseDeserializer deserializer,
  );

  @protected
  NativeRagIndexResponse sse_decode_native_rag_index_response(
    SseDeserializer deserializer,
  );

  @protected
  NativeRagQueryRequest sse_decode_native_rag_query_request(
    SseDeserializer deserializer,
  );

  @protected
  NativeRagQueryResponse sse_decode_native_rag_query_response(
    SseDeserializer deserializer,
  );

  @protected
  NativeRagQueryResult sse_decode_native_rag_query_result(
    SseDeserializer deserializer,
  );

  @protected
  NativeSceneObject sse_decode_native_scene_object(
    SseDeserializer deserializer,
  );

  @protected
  NativeSceneObjectKind sse_decode_native_scene_object_kind(
    SseDeserializer deserializer,
  );

  @protected
  NativeSubmitCommandRequest sse_decode_native_submit_command_request(
    SseDeserializer deserializer,
  );

  @protected
  NativeTextRun sse_decode_native_text_run(SseDeserializer deserializer);

  @protected
  NativeTextStyle sse_decode_native_text_style(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  NativeAffineTransform? sse_decode_opt_box_autoadd_native_affine_transform(
    SseDeserializer deserializer,
  );

  @protected
  NativeCommandResult? sse_decode_opt_box_autoadd_native_command_result(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfBox? sse_decode_opt_box_autoadd_native_pdf_box(
    SseDeserializer deserializer,
  );

  @protected
  NativeTextStyle? sse_decode_opt_box_autoadd_native_text_style(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<NativeTextRun>? sse_decode_opt_list_native_text_run(
    SseDeserializer deserializer,
  );

  @protected
  PdfDocumentMetadata sse_decode_pdf_document_metadata(
    SseDeserializer deserializer,
  );

  @protected
  PdfSearchMatch sse_decode_pdf_search_match(SseDeserializer deserializer);

  @protected
  (double, double, double, double) sse_decode_record_f_32_f_32_f_32_f_32(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    NativeEditorSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    NativeEditorSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    NativeEditorSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_native_editor_event_Sse(
    RustStreamSink<NativeEditorEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_native_affine_transform(
    NativeAffineTransform self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_command_result(
    NativeCommandResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_open_editor_request(
    NativeOpenEditorRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_page_scene_request(
    NativePageSceneRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_pdf_box(
    NativePdfBox self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_pdf_compose_request(
    NativePdfComposeRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_pdf_save_request(
    NativePdfSaveRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_rag_index_request(
    NativeRagIndexRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_rag_query_request(
    NativeRagQueryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_submit_command_request(
    NativeSubmitCommandRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_text_style(
    NativeTextStyle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_native_object_patch(
    List<NativeObjectPatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_pdf_bookmark(
    List<NativePdfBookmark> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_pdf_highlight(
    List<NativePdfHighlight> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_pdf_source(
    List<NativePdfSource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_rag_chunk(
    List<NativeRagChunk> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_rag_query_result(
    List<NativeRagQueryResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_scene_object(
    List<NativeSceneObject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_text_run(
    List<NativeTextRun> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pdf_search_match(
    List<PdfSearchMatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_usize_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_affine_transform(
    NativeAffineTransform self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_command_result(
    NativeCommandResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_editor_command(
    NativeEditorCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_editor_command_kind(
    NativeEditorCommandKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_editor_event(
    NativeEditorEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_editor_event_kind(
    NativeEditorEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_editor_metadata(
    NativeEditorMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_object_patch(
    NativeObjectPatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_open_editor_request(
    NativeOpenEditorRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_page_scene(
    NativePageScene self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_page_scene_request(
    NativePageSceneRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_pdf_annotations(
    NativePdfAnnotations self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_pdf_bookmark(
    NativePdfBookmark self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_pdf_box(NativePdfBox self, SseSerializer serializer);

  @protected
  void sse_encode_native_pdf_compose_request(
    NativePdfComposeRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_pdf_compose_response(
    NativePdfComposeResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_pdf_highlight(
    NativePdfHighlight self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_pdf_save_request(
    NativePdfSaveRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_pdf_source(
    NativePdfSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_chunk(
    NativeRagChunk self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_index_request(
    NativeRagIndexRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_index_response(
    NativeRagIndexResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_query_request(
    NativeRagQueryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_query_response(
    NativeRagQueryResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_query_result(
    NativeRagQueryResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_scene_object(
    NativeSceneObject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_scene_object_kind(
    NativeSceneObjectKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_submit_command_request(
    NativeSubmitCommandRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_text_run(NativeTextRun self, SseSerializer serializer);

  @protected
  void sse_encode_native_text_style(
    NativeTextStyle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_native_affine_transform(
    NativeAffineTransform? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_native_command_result(
    NativeCommandResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_native_pdf_box(
    NativePdfBox? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_native_text_style(
    NativeTextStyle? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_native_text_run(
    List<NativeTextRun>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_document_metadata(
    PdfDocumentMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_search_match(
    PdfSearchMatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_f_32_f_32_f_32_f_32(
    (double, double, double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeEditorSession(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    int ptr,
  );
}
