// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'chat_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1334447033;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'clarix_pdf_oxide',
        ioDirectory: 'rust/clarix_pdf_oxide/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<String> crateApiNativePdfSessionIndex({
    required NativePdfSession that,
    required BigInt maxCharsPerChunk,
    required BigInt batchSize,
  });

  Future<PdfDocumentMetadata> crateApiNativePdfSessionMetadata({
    required NativePdfSession that,
  });

  Future<NativePdfSession> crateApiNativePdfSessionOpen({required String path});

  Future<String> crateApiNativePdfSessionPageText({
    required NativePdfSession that,
    required BigInt pageNumber,
  });

  Future<List<PdfSearchMatch>> crateApiNativePdfSessionSearch({
    required NativePdfSession that,
    required String query,
  });

  Future<NativePdfComposeResponse> crateApiComposePdfs({
    required NativePdfComposeRequest request,
  });

  Future<NativeRagIndexResponse> crateApiLocalRagIndex({
    required NativeRagIndexRequest request,
  });

  Future<NativeRagQueryResponse> crateApiLocalRagQuery({
    required NativeRagQueryRequest request,
  });

  Future<String> crateApiLocalRagStatus({
    required String storageDirectory,
    required String documentFingerprint,
  });

  Future<NativeRagIndexResponse> crateApiLocalRagValidate({
    required NativeRagIndexRequest request,
  });

  Future<NativeChatEvent?> crateChatApiParseChatSseData({required String data});

  Future<NativePdfAnnotations> crateApiReadPdfAnnotations({
    required String path,
  });

  Future<void> crateApiSavePdfAnnotations({
    required NativePdfSaveRequest request,
  });

  Stream<NativeChatEvent> crateChatApiStreamChat({
    required NativeChatRequest request,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NativePdfSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NativePdfSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NativePdfSessionPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<String> crateApiNativePdfSessionIndex({
    required NativePdfSession that,
    required BigInt maxCharsPerChunk,
    required BigInt batchSize,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
              that,
              serializer,
            );
            sse_encode_usize(maxCharsPerChunk, serializer);
            sse_encode_usize(batchSize, serializer);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiNativePdfSessionIndexConstMeta,
          argValues: [that, maxCharsPerChunk, batchSize, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiNativePdfSessionIndexConstMeta =>
      const TaskConstMeta(
        debugName: "NativePdfSession_index",
        argNames: ["that", "maxCharsPerChunk", "batchSize", "sink"],
      );

  @override
  Future<PdfDocumentMetadata> crateApiNativePdfSessionMetadata({
    required NativePdfSession that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pdf_document_metadata,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNativePdfSessionMetadataConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNativePdfSessionMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "NativePdfSession_metadata",
        argNames: ["that"],
      );

  @override
  Future<NativePdfSession> crateApiNativePdfSessionOpen({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNativePdfSessionOpenConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNativePdfSessionOpenConstMeta =>
      const TaskConstMeta(
        debugName: "NativePdfSession_open",
        argNames: ["path"],
      );

  @override
  Future<String> crateApiNativePdfSessionPageText({
    required NativePdfSession that,
    required BigInt pageNumber,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
            that,
            serializer,
          );
          sse_encode_usize(pageNumber, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNativePdfSessionPageTextConstMeta,
        argValues: [that, pageNumber],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNativePdfSessionPageTextConstMeta =>
      const TaskConstMeta(
        debugName: "NativePdfSession_page_text",
        argNames: ["that", "pageNumber"],
      );

  @override
  Future<List<PdfSearchMatch>> crateApiNativePdfSessionSearch({
    required NativePdfSession that,
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pdf_search_match,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNativePdfSessionSearchConstMeta,
        argValues: [that, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNativePdfSessionSearchConstMeta =>
      const TaskConstMeta(
        debugName: "NativePdfSession_search",
        argNames: ["that", "query"],
      );

  @override
  Future<NativePdfComposeResponse> crateApiComposePdfs({
    required NativePdfComposeRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_native_pdf_compose_request(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_pdf_compose_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiComposePdfsConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComposePdfsConstMeta =>
      const TaskConstMeta(debugName: "compose_pdfs", argNames: ["request"]);

  @override
  Future<NativeRagIndexResponse> crateApiLocalRagIndex({
    required NativeRagIndexRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_native_rag_index_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_rag_index_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocalRagIndexConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocalRagIndexConstMeta =>
      const TaskConstMeta(debugName: "local_rag_index", argNames: ["request"]);

  @override
  Future<NativeRagQueryResponse> crateApiLocalRagQuery({
    required NativeRagQueryRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_native_rag_query_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_rag_query_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocalRagQueryConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocalRagQueryConstMeta =>
      const TaskConstMeta(debugName: "local_rag_query", argNames: ["request"]);

  @override
  Future<String> crateApiLocalRagStatus({
    required String storageDirectory,
    required String documentFingerprint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(storageDirectory, serializer);
          sse_encode_String(documentFingerprint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocalRagStatusConstMeta,
        argValues: [storageDirectory, documentFingerprint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocalRagStatusConstMeta => const TaskConstMeta(
    debugName: "local_rag_status",
    argNames: ["storageDirectory", "documentFingerprint"],
  );

  @override
  Future<NativeRagIndexResponse> crateApiLocalRagValidate({
    required NativeRagIndexRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_native_rag_index_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_rag_index_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLocalRagValidateConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLocalRagValidateConstMeta => const TaskConstMeta(
    debugName: "local_rag_validate",
    argNames: ["request"],
  );

  @override
  Future<NativeChatEvent?> crateChatApiParseChatSseData({
    required String data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_native_chat_event,
          decodeErrorData: null,
        ),
        constMeta: kCrateChatApiParseChatSseDataConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateChatApiParseChatSseDataConstMeta =>
      const TaskConstMeta(debugName: "parse_chat_sse_data", argNames: ["data"]);

  @override
  Future<NativePdfAnnotations> crateApiReadPdfAnnotations({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_pdf_annotations,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadPdfAnnotationsConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadPdfAnnotationsConstMeta => const TaskConstMeta(
    debugName: "read_pdf_annotations",
    argNames: ["path"],
  );

  @override
  Future<void> crateApiSavePdfAnnotations({
    required NativePdfSaveRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_native_pdf_save_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSavePdfAnnotationsConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSavePdfAnnotationsConstMeta => const TaskConstMeta(
    debugName: "save_pdf_annotations",
    argNames: ["request"],
  );

  @override
  Stream<NativeChatEvent> crateChatApiStreamChat({
    required NativeChatRequest request,
  }) {
    final sink = RustStreamSink<NativeChatEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_native_chat_request(request, serializer);
            sse_encode_StreamSink_native_chat_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 14,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateChatApiStreamChatConstMeta,
          argValues: [request, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateChatApiStreamChatConstMeta => const TaskConstMeta(
    debugName: "stream_chat",
    argNames: ["request", "sink"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NativePdfSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NativePdfSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  NativePdfSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativePdfSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NativePdfSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativePdfSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NativePdfSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativePdfSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_string(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  NativePdfSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativePdfSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<NativeChatEvent> dco_decode_StreamSink_native_chat_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  NativeChatEvent dco_decode_box_autoadd_native_chat_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_native_chat_event(raw);
  }

  @protected
  NativeChatRequest dco_decode_box_autoadd_native_chat_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_native_chat_request(raw);
  }

  @protected
  NativePdfComposeRequest dco_decode_box_autoadd_native_pdf_compose_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_native_pdf_compose_request(raw);
  }

  @protected
  NativePdfSaveRequest dco_decode_box_autoadd_native_pdf_save_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_native_pdf_save_request(raw);
  }

  @protected
  NativeRagIndexRequest dco_decode_box_autoadd_native_rag_index_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_native_rag_index_request(raw);
  }

  @protected
  NativeRagQueryRequest dco_decode_box_autoadd_native_rag_query_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_native_rag_query_request(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<NativeChatMessage> dco_decode_list_native_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_native_chat_message).toList();
  }

  @protected
  List<NativePdfBookmark> dco_decode_list_native_pdf_bookmark(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_native_pdf_bookmark).toList();
  }

  @protected
  List<NativePdfHighlight> dco_decode_list_native_pdf_highlight(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_native_pdf_highlight).toList();
  }

  @protected
  List<NativePdfSource> dco_decode_list_native_pdf_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_native_pdf_source).toList();
  }

  @protected
  List<NativeRagChunk> dco_decode_list_native_rag_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_native_rag_chunk).toList();
  }

  @protected
  List<NativeRagQueryResult> dco_decode_list_native_rag_query_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_native_rag_query_result)
        .toList();
  }

  @protected
  List<PdfSearchMatch> dco_decode_list_pdf_search_match(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pdf_search_match).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint64List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  NativeChatEvent dco_decode_native_chat_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return NativeChatEvent_TextDelta(text: dco_decode_String(raw[1]));
      case 1:
        return NativeChatEvent_Error(message: dco_decode_String(raw[1]));
      case 2:
        return NativeChatEvent_Done();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  NativeChatMessage dco_decode_native_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NativeChatMessage(
      role: dco_decode_String(arr[0]),
      content: dco_decode_String(arr[1]),
    );
  }

  @protected
  NativeChatRequest dco_decode_native_chat_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NativeChatRequest(
      providerEndpoint: dco_decode_String(arr[0]),
      modelId: dco_decode_String(arr[1]),
      headers: dco_decode_Map_String_String_None(arr[2]),
      apiKey: dco_decode_String(arr[3]),
      messages: dco_decode_list_native_chat_message(arr[4]),
    );
  }

  @protected
  NativePdfAnnotations dco_decode_native_pdf_annotations(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NativePdfAnnotations(
      bookmarks: dco_decode_list_native_pdf_bookmark(arr[0]),
      highlights: dco_decode_list_native_pdf_highlight(arr[1]),
    );
  }

  @protected
  NativePdfBookmark dco_decode_native_pdf_bookmark(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NativePdfBookmark(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      pageNumber: dco_decode_usize(arr[2]),
    );
  }

  @protected
  NativePdfComposeRequest dco_decode_native_pdf_compose_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NativePdfComposeRequest(
      sources: dco_decode_list_native_pdf_source(arr[0]),
      outputPath: dco_decode_String(arr[1]),
    );
  }

  @protected
  NativePdfComposeResponse dco_decode_native_pdf_compose_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NativePdfComposeResponse(
      outputPath: dco_decode_String(arr[0]),
      pageCount: dco_decode_usize(arr[1]),
      message: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  NativePdfHighlight dco_decode_native_pdf_highlight(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return NativePdfHighlight(
      id: dco_decode_String(arr[0]),
      pageNumber: dco_decode_usize(arr[1]),
      left: dco_decode_f_32(arr[2]),
      top: dco_decode_f_32(arr[3]),
      right: dco_decode_f_32(arr[4]),
      bottom: dco_decode_f_32(arr[5]),
      red: dco_decode_f_32(arr[6]),
      green: dco_decode_f_32(arr[7]),
      blue: dco_decode_f_32(arr[8]),
      opacity: dco_decode_f_32(arr[9]),
      text: dco_decode_String(arr[10]),
      quadPoints: dco_decode_list_prim_f_32_strict(arr[11]),
    );
  }

  @protected
  NativePdfSaveRequest dco_decode_native_pdf_save_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NativePdfSaveRequest(
      path: dco_decode_String(arr[0]),
      outputPath: dco_decode_opt_String(arr[1]),
      bookmarks: dco_decode_list_native_pdf_bookmark(arr[2]),
      highlights: dco_decode_list_native_pdf_highlight(arr[3]),
    );
  }

  @protected
  NativePdfSource dco_decode_native_pdf_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NativePdfSource(
      path: dco_decode_String(arr[0]),
      pages: dco_decode_list_prim_usize_strict(arr[1]),
    );
  }

  @protected
  NativeRagChunk dco_decode_native_rag_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NativeRagChunk(
      id: dco_decode_String(arr[0]),
      text: dco_decode_String(arr[1]),
    );
  }

  @protected
  NativeRagIndexRequest dco_decode_native_rag_index_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NativeRagIndexRequest(
      storageDirectory: dco_decode_String(arr[0]),
      modelCacheDirectory: dco_decode_String(arr[1]),
      documentFingerprint: dco_decode_String(arr[2]),
      chunks: dco_decode_list_native_rag_chunk(arr[3]),
    );
  }

  @protected
  NativeRagIndexResponse dco_decode_native_rag_index_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NativeRagIndexResponse(
      status: dco_decode_String(arr[0]),
      message: dco_decode_opt_String(arr[1]),
      outcome: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  NativeRagQueryRequest dco_decode_native_rag_query_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return NativeRagQueryRequest(
      storageDirectory: dco_decode_String(arr[0]),
      modelCacheDirectory: dco_decode_String(arr[1]),
      documentFingerprint: dco_decode_String(arr[2]),
      chunkIds: dco_decode_list_String(arr[3]),
      query: dco_decode_String(arr[4]),
      limit: dco_decode_usize(arr[5]),
    );
  }

  @protected
  NativeRagQueryResponse dco_decode_native_rag_query_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NativeRagQueryResponse(
      status: dco_decode_String(arr[0]),
      message: dco_decode_opt_String(arr[1]),
      results: dco_decode_list_native_rag_query_result(arr[2]),
    );
  }

  @protected
  NativeRagQueryResult dco_decode_native_rag_query_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NativeRagQueryResult(
      chunkId: dco_decode_String(arr[0]),
      score: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  NativeChatEvent? dco_decode_opt_box_autoadd_native_chat_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_native_chat_event(raw);
  }

  @protected
  PdfDocumentMetadata dco_decode_pdf_document_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PdfDocumentMetadata(
      documentId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      pageCount: dco_decode_usize(arr[2]),
      isEncrypted: dco_decode_bool(arr[3]),
    );
  }

  @protected
  PdfSearchMatch dco_decode_pdf_search_match(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PdfSearchMatch(
      pageNumber: dco_decode_usize(arr[0]),
      text: dco_decode_String(arr[1]),
      bounds: dco_decode_record_f_32_f_32_f_32_f_32(arr[2]),
    );
  }

  @protected
  (double, double, double, double) dco_decode_record_f_32_f_32_f_32_f_32(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) {
      throw Exception('Expected 4 elements, got ${arr.length}');
    }
    return (
      dco_decode_f_32(arr[0]),
      dco_decode_f_32(arr[1]),
      dco_decode_f_32(arr[2]),
      dco_decode_f_32(arr[3]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  NativePdfSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativePdfSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NativePdfSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativePdfSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NativePdfSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativePdfSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  NativePdfSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativePdfSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<NativeChatEvent> sse_decode_StreamSink_native_chat_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  NativeChatEvent sse_decode_box_autoadd_native_chat_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_native_chat_event(deserializer));
  }

  @protected
  NativeChatRequest sse_decode_box_autoadd_native_chat_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_native_chat_request(deserializer));
  }

  @protected
  NativePdfComposeRequest sse_decode_box_autoadd_native_pdf_compose_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_native_pdf_compose_request(deserializer));
  }

  @protected
  NativePdfSaveRequest sse_decode_box_autoadd_native_pdf_save_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_native_pdf_save_request(deserializer));
  }

  @protected
  NativeRagIndexRequest sse_decode_box_autoadd_native_rag_index_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_native_rag_index_request(deserializer));
  }

  @protected
  NativeRagQueryRequest sse_decode_box_autoadd_native_rag_query_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_native_rag_query_request(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeChatMessage> sse_decode_list_native_chat_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeChatMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_chat_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativePdfBookmark> sse_decode_list_native_pdf_bookmark(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativePdfBookmark>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_pdf_bookmark(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativePdfHighlight> sse_decode_list_native_pdf_highlight(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativePdfHighlight>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_pdf_highlight(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativePdfSource> sse_decode_list_native_pdf_source(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativePdfSource>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_pdf_source(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeRagChunk> sse_decode_list_native_rag_chunk(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeRagChunk>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_rag_chunk(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeRagQueryResult> sse_decode_list_native_rag_query_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeRagQueryResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_rag_query_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<PdfSearchMatch> sse_decode_list_pdf_search_match(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PdfSearchMatch>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pdf_search_match(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  NativeChatEvent sse_decode_native_chat_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_text = sse_decode_String(deserializer);
        return NativeChatEvent_TextDelta(text: var_text);
      case 1:
        var var_message = sse_decode_String(deserializer);
        return NativeChatEvent_Error(message: var_message);
      case 2:
        return NativeChatEvent_Done();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  NativeChatMessage sse_decode_native_chat_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_role = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    return NativeChatMessage(role: var_role, content: var_content);
  }

  @protected
  NativeChatRequest sse_decode_native_chat_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_providerEndpoint = sse_decode_String(deserializer);
    var var_modelId = sse_decode_String(deserializer);
    var var_headers = sse_decode_Map_String_String_None(deserializer);
    var var_apiKey = sse_decode_String(deserializer);
    var var_messages = sse_decode_list_native_chat_message(deserializer);
    return NativeChatRequest(
      providerEndpoint: var_providerEndpoint,
      modelId: var_modelId,
      headers: var_headers,
      apiKey: var_apiKey,
      messages: var_messages,
    );
  }

  @protected
  NativePdfAnnotations sse_decode_native_pdf_annotations(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bookmarks = sse_decode_list_native_pdf_bookmark(deserializer);
    var var_highlights = sse_decode_list_native_pdf_highlight(deserializer);
    return NativePdfAnnotations(
      bookmarks: var_bookmarks,
      highlights: var_highlights,
    );
  }

  @protected
  NativePdfBookmark sse_decode_native_pdf_bookmark(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_pageNumber = sse_decode_usize(deserializer);
    return NativePdfBookmark(
      id: var_id,
      title: var_title,
      pageNumber: var_pageNumber,
    );
  }

  @protected
  NativePdfComposeRequest sse_decode_native_pdf_compose_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sources = sse_decode_list_native_pdf_source(deserializer);
    var var_outputPath = sse_decode_String(deserializer);
    return NativePdfComposeRequest(
      sources: var_sources,
      outputPath: var_outputPath,
    );
  }

  @protected
  NativePdfComposeResponse sse_decode_native_pdf_compose_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputPath = sse_decode_String(deserializer);
    var var_pageCount = sse_decode_usize(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    return NativePdfComposeResponse(
      outputPath: var_outputPath,
      pageCount: var_pageCount,
      message: var_message,
    );
  }

  @protected
  NativePdfHighlight sse_decode_native_pdf_highlight(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_pageNumber = sse_decode_usize(deserializer);
    var var_left = sse_decode_f_32(deserializer);
    var var_top = sse_decode_f_32(deserializer);
    var var_right = sse_decode_f_32(deserializer);
    var var_bottom = sse_decode_f_32(deserializer);
    var var_red = sse_decode_f_32(deserializer);
    var var_green = sse_decode_f_32(deserializer);
    var var_blue = sse_decode_f_32(deserializer);
    var var_opacity = sse_decode_f_32(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_quadPoints = sse_decode_list_prim_f_32_strict(deserializer);
    return NativePdfHighlight(
      id: var_id,
      pageNumber: var_pageNumber,
      left: var_left,
      top: var_top,
      right: var_right,
      bottom: var_bottom,
      red: var_red,
      green: var_green,
      blue: var_blue,
      opacity: var_opacity,
      text: var_text,
      quadPoints: var_quadPoints,
    );
  }

  @protected
  NativePdfSaveRequest sse_decode_native_pdf_save_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_outputPath = sse_decode_opt_String(deserializer);
    var var_bookmarks = sse_decode_list_native_pdf_bookmark(deserializer);
    var var_highlights = sse_decode_list_native_pdf_highlight(deserializer);
    return NativePdfSaveRequest(
      path: var_path,
      outputPath: var_outputPath,
      bookmarks: var_bookmarks,
      highlights: var_highlights,
    );
  }

  @protected
  NativePdfSource sse_decode_native_pdf_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_pages = sse_decode_list_prim_usize_strict(deserializer);
    return NativePdfSource(path: var_path, pages: var_pages);
  }

  @protected
  NativeRagChunk sse_decode_native_rag_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    return NativeRagChunk(id: var_id, text: var_text);
  }

  @protected
  NativeRagIndexRequest sse_decode_native_rag_index_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_storageDirectory = sse_decode_String(deserializer);
    var var_modelCacheDirectory = sse_decode_String(deserializer);
    var var_documentFingerprint = sse_decode_String(deserializer);
    var var_chunks = sse_decode_list_native_rag_chunk(deserializer);
    return NativeRagIndexRequest(
      storageDirectory: var_storageDirectory,
      modelCacheDirectory: var_modelCacheDirectory,
      documentFingerprint: var_documentFingerprint,
      chunks: var_chunks,
    );
  }

  @protected
  NativeRagIndexResponse sse_decode_native_rag_index_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_String(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    var var_outcome = sse_decode_opt_String(deserializer);
    return NativeRagIndexResponse(
      status: var_status,
      message: var_message,
      outcome: var_outcome,
    );
  }

  @protected
  NativeRagQueryRequest sse_decode_native_rag_query_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_storageDirectory = sse_decode_String(deserializer);
    var var_modelCacheDirectory = sse_decode_String(deserializer);
    var var_documentFingerprint = sse_decode_String(deserializer);
    var var_chunkIds = sse_decode_list_String(deserializer);
    var var_query = sse_decode_String(deserializer);
    var var_limit = sse_decode_usize(deserializer);
    return NativeRagQueryRequest(
      storageDirectory: var_storageDirectory,
      modelCacheDirectory: var_modelCacheDirectory,
      documentFingerprint: var_documentFingerprint,
      chunkIds: var_chunkIds,
      query: var_query,
      limit: var_limit,
    );
  }

  @protected
  NativeRagQueryResponse sse_decode_native_rag_query_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_String(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    var var_results = sse_decode_list_native_rag_query_result(deserializer);
    return NativeRagQueryResponse(
      status: var_status,
      message: var_message,
      results: var_results,
    );
  }

  @protected
  NativeRagQueryResult sse_decode_native_rag_query_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chunkId = sse_decode_String(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    return NativeRagQueryResult(chunkId: var_chunkId, score: var_score);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NativeChatEvent? sse_decode_opt_box_autoadd_native_chat_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_native_chat_event(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PdfDocumentMetadata sse_decode_pdf_document_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_documentId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_pageCount = sse_decode_usize(deserializer);
    var var_isEncrypted = sse_decode_bool(deserializer);
    return PdfDocumentMetadata(
      documentId: var_documentId,
      title: var_title,
      pageCount: var_pageCount,
      isEncrypted: var_isEncrypted,
    );
  }

  @protected
  PdfSearchMatch sse_decode_pdf_search_match(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pageNumber = sse_decode_usize(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_bounds = sse_decode_record_f_32_f_32_f_32_f_32(deserializer);
    return PdfSearchMatch(
      pageNumber: var_pageNumber,
      text: var_text,
      bounds: var_bounds,
    );
  }

  @protected
  (double, double, double, double) sse_decode_record_f_32_f_32_f_32_f_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_32(deserializer);
    var var_field1 = sse_decode_f_32(deserializer);
    var var_field2 = sse_decode_f_32(deserializer);
    var var_field3 = sse_decode_f_32(deserializer);
    return (var_field0, var_field1, var_field2, var_field3);
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativePdfSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativePdfSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativePdfSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativePdfSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_native_chat_event_Sse(
    RustStreamSink<NativeChatEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_chat_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_native_chat_event(
    NativeChatEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_native_chat_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_native_chat_request(
    NativeChatRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_native_chat_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_native_pdf_compose_request(
    NativePdfComposeRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_native_pdf_compose_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_native_pdf_save_request(
    NativePdfSaveRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_native_pdf_save_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_native_rag_index_request(
    NativeRagIndexRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_native_rag_index_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_native_rag_query_request(
    NativeRagQueryRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_native_rag_query_request(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_chat_message(
    List<NativeChatMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_chat_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_pdf_bookmark(
    List<NativePdfBookmark> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_pdf_bookmark(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_pdf_highlight(
    List<NativePdfHighlight> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_pdf_highlight(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_pdf_source(
    List<NativePdfSource> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_pdf_source(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_rag_chunk(
    List<NativeRagChunk> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_rag_chunk(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_rag_query_result(
    List<NativeRagQueryResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_rag_query_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pdf_search_match(
    List<PdfSearchMatch> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pdf_search_match(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_prim_usize_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_native_chat_event(
    NativeChatEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case NativeChatEvent_TextDelta(text: final text):
        sse_encode_i_32(0, serializer);
        sse_encode_String(text, serializer);
      case NativeChatEvent_Error(message: final message):
        sse_encode_i_32(1, serializer);
        sse_encode_String(message, serializer);
      case NativeChatEvent_Done():
        sse_encode_i_32(2, serializer);
    }
  }

  @protected
  void sse_encode_native_chat_message(
    NativeChatMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.content, serializer);
  }

  @protected
  void sse_encode_native_chat_request(
    NativeChatRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.providerEndpoint, serializer);
    sse_encode_String(self.modelId, serializer);
    sse_encode_Map_String_String_None(self.headers, serializer);
    sse_encode_String(self.apiKey, serializer);
    sse_encode_list_native_chat_message(self.messages, serializer);
  }

  @protected
  void sse_encode_native_pdf_annotations(
    NativePdfAnnotations self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_native_pdf_bookmark(self.bookmarks, serializer);
    sse_encode_list_native_pdf_highlight(self.highlights, serializer);
  }

  @protected
  void sse_encode_native_pdf_bookmark(
    NativePdfBookmark self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_usize(self.pageNumber, serializer);
  }

  @protected
  void sse_encode_native_pdf_compose_request(
    NativePdfComposeRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_native_pdf_source(self.sources, serializer);
    sse_encode_String(self.outputPath, serializer);
  }

  @protected
  void sse_encode_native_pdf_compose_response(
    NativePdfComposeResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outputPath, serializer);
    sse_encode_usize(self.pageCount, serializer);
    sse_encode_opt_String(self.message, serializer);
  }

  @protected
  void sse_encode_native_pdf_highlight(
    NativePdfHighlight self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_usize(self.pageNumber, serializer);
    sse_encode_f_32(self.left, serializer);
    sse_encode_f_32(self.top, serializer);
    sse_encode_f_32(self.right, serializer);
    sse_encode_f_32(self.bottom, serializer);
    sse_encode_f_32(self.red, serializer);
    sse_encode_f_32(self.green, serializer);
    sse_encode_f_32(self.blue, serializer);
    sse_encode_f_32(self.opacity, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_list_prim_f_32_strict(self.quadPoints, serializer);
  }

  @protected
  void sse_encode_native_pdf_save_request(
    NativePdfSaveRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_opt_String(self.outputPath, serializer);
    sse_encode_list_native_pdf_bookmark(self.bookmarks, serializer);
    sse_encode_list_native_pdf_highlight(self.highlights, serializer);
  }

  @protected
  void sse_encode_native_pdf_source(
    NativePdfSource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_list_prim_usize_strict(self.pages, serializer);
  }

  @protected
  void sse_encode_native_rag_chunk(
    NativeRagChunk self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_native_rag_index_request(
    NativeRagIndexRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.storageDirectory, serializer);
    sse_encode_String(self.modelCacheDirectory, serializer);
    sse_encode_String(self.documentFingerprint, serializer);
    sse_encode_list_native_rag_chunk(self.chunks, serializer);
  }

  @protected
  void sse_encode_native_rag_index_response(
    NativeRagIndexResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.status, serializer);
    sse_encode_opt_String(self.message, serializer);
    sse_encode_opt_String(self.outcome, serializer);
  }

  @protected
  void sse_encode_native_rag_query_request(
    NativeRagQueryRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.storageDirectory, serializer);
    sse_encode_String(self.modelCacheDirectory, serializer);
    sse_encode_String(self.documentFingerprint, serializer);
    sse_encode_list_String(self.chunkIds, serializer);
    sse_encode_String(self.query, serializer);
    sse_encode_usize(self.limit, serializer);
  }

  @protected
  void sse_encode_native_rag_query_response(
    NativeRagQueryResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.status, serializer);
    sse_encode_opt_String(self.message, serializer);
    sse_encode_list_native_rag_query_result(self.results, serializer);
  }

  @protected
  void sse_encode_native_rag_query_result(
    NativeRagQueryResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.chunkId, serializer);
    sse_encode_f_32(self.score, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_native_chat_event(
    NativeChatEvent? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_native_chat_event(self, serializer);
    }
  }

  @protected
  void sse_encode_pdf_document_metadata(
    PdfDocumentMetadata self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.documentId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_usize(self.pageCount, serializer);
    sse_encode_bool(self.isEncrypted, serializer);
  }

  @protected
  void sse_encode_pdf_search_match(
    PdfSearchMatch self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.pageNumber, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_record_f_32_f_32_f_32_f_32(self.bounds, serializer);
  }

  @protected
  void sse_encode_record_f_32_f_32_f_32_f_32(
    (double, double, double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.$1, serializer);
    sse_encode_f_32(self.$2, serializer);
    sse_encode_f_32(self.$3, serializer);
    sse_encode_f_32(self.$4, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class NativePdfSessionImpl extends RustOpaque implements NativePdfSession {
  // Not to be used by end users
  NativePdfSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NativePdfSessionImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_NativePdfSession,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_NativePdfSession,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_NativePdfSessionPtr,
  );

  Stream<String> index({
    required BigInt maxCharsPerChunk,
    required BigInt batchSize,
  }) => RustLib.instance.api.crateApiNativePdfSessionIndex(
    that: this,
    maxCharsPerChunk: maxCharsPerChunk,
    batchSize: batchSize,
  );

  Future<PdfDocumentMetadata> metadata() =>
      RustLib.instance.api.crateApiNativePdfSessionMetadata(that: this);

  Future<String> pageText({required BigInt pageNumber}) => RustLib.instance.api
      .crateApiNativePdfSessionPageText(that: this, pageNumber: pageNumber);

  Future<List<PdfSearchMatch>> search({required String query}) => RustLib
      .instance
      .api
      .crateApiNativePdfSessionSearch(that: this, query: query);
}
