// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NativePdfSessionPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSessionPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  NativePdfSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  );

  @protected
  NativePdfSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  );

  @protected
  NativePdfSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  );

  @protected
  NativePdfSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    dynamic raw,
  );

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  NativeRagIndexRequest dco_decode_box_autoadd_native_rag_index_request(
    dynamic raw,
  );

  @protected
  NativeRagQueryRequest dco_decode_box_autoadd_native_rag_query_request(
    dynamic raw,
  );

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<NativeRagChunk> dco_decode_list_native_rag_chunk(dynamic raw);

  @protected
  List<NativeRagQueryResult> dco_decode_list_native_rag_query_result(
    dynamic raw,
  );

  @protected
  List<PdfSearchMatch> dco_decode_list_pdf_search_match(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NativeRagChunk dco_decode_native_rag_chunk(dynamic raw);

  @protected
  NativeRagIndexRequest dco_decode_native_rag_index_request(dynamic raw);

  @protected
  NativeRagIndexResponse dco_decode_native_rag_index_response(dynamic raw);

  @protected
  NativeRagQueryRequest dco_decode_native_rag_query_request(dynamic raw);

  @protected
  NativeRagQueryResponse dco_decode_native_rag_query_response(dynamic raw);

  @protected
  NativeRagQueryResult dco_decode_native_rag_query_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PdfDocumentMetadata dco_decode_pdf_document_metadata(dynamic raw);

  @protected
  PdfSearchMatch dco_decode_pdf_search_match(dynamic raw);

  @protected
  (double, double, double, double) dco_decode_record_f_32_f_32_f_32_f_32(
    dynamic raw,
  );

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  NativePdfSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  );

  @protected
  NativePdfSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  NativeRagIndexRequest sse_decode_box_autoadd_native_rag_index_request(
    SseDeserializer deserializer,
  );

  @protected
  NativeRagQueryRequest sse_decode_box_autoadd_native_rag_query_request(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<NativeRagChunk> sse_decode_list_native_rag_chunk(
    SseDeserializer deserializer,
  );

  @protected
  List<NativeRagQueryResult> sse_decode_list_native_rag_query_result(
    SseDeserializer deserializer,
  );

  @protected
  List<PdfSearchMatch> sse_decode_list_pdf_search_match(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NativeRagChunk sse_decode_native_rag_chunk(SseDeserializer deserializer);

  @protected
  NativeRagIndexRequest sse_decode_native_rag_index_request(
    SseDeserializer deserializer,
  );

  @protected
  NativeRagIndexResponse sse_decode_native_rag_index_response(
    SseDeserializer deserializer,
  );

  @protected
  NativeRagQueryRequest sse_decode_native_rag_query_request(
    SseDeserializer deserializer,
  );

  @protected
  NativeRagQueryResponse sse_decode_native_rag_query_response(
    SseDeserializer deserializer,
  );

  @protected
  NativeRagQueryResult sse_decode_native_rag_query_result(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PdfDocumentMetadata sse_decode_pdf_document_metadata(
    SseDeserializer deserializer,
  );

  @protected
  PdfSearchMatch sse_decode_pdf_search_match(SseDeserializer deserializer);

  @protected
  (double, double, double, double) sse_decode_record_f_32_f_32_f_32_f_32(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    NativePdfSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_native_rag_index_request(
    NativeRagIndexRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_rag_query_request(
    NativeRagQueryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_native_rag_chunk(
    List<NativeRagChunk> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_rag_query_result(
    List<NativeRagQueryResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pdf_search_match(
    List<PdfSearchMatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_chunk(
    NativeRagChunk self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_index_request(
    NativeRagIndexRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_index_response(
    NativeRagIndexResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_query_request(
    NativeRagQueryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_query_response(
    NativeRagQueryResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_rag_query_result(
    NativeRagQueryResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_pdf_document_metadata(
    PdfDocumentMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pdf_search_match(
    PdfSearchMatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_f_32_f_32_f_32_f_32(
    (double, double, double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_clarix_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_clarix_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSession =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativePdfSessionPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
