// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PdfDocumentMetadata {
  final String documentId;
  final String title;
  final BigInt pageCount;
  final bool isEncrypted;

  const PdfDocumentMetadata({
    required this.documentId,
    required this.title,
    required this.pageCount,
    required this.isEncrypted,
  });

  @override
  int get hashCode =>
      documentId.hashCode ^
      title.hashCode ^
      pageCount.hashCode ^
      isEncrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdfDocumentMetadata &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          title == other.title &&
          pageCount == other.pageCount &&
          isEncrypted == other.isEncrypted;
}

class PdfSearchMatch {
  final BigInt pageNumber;
  final String text;
  final (double, double, double, double) bounds;

  const PdfSearchMatch({
    required this.pageNumber,
    required this.text,
    required this.bounds,
  });

  @override
  int get hashCode => pageNumber.hashCode ^ text.hashCode ^ bounds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdfSearchMatch &&
          runtimeType == other.runtimeType &&
          pageNumber == other.pageNumber &&
          text == other.text &&
          bounds == other.bounds;
}
